/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Service
 */
interface Service {
  /** Contains additional information about the payment. Some data fields are included only if you select them first. Go to **Customer Area** > **Developers** > **Additional data**. */
  additionalData?: Record<string, string>;
  /** The error code mapped to the error message. */
  errorCode?: string;
  /** The category of the error. */
  errorType?: string;
  /** A short explanation of the issue. */
  message?: string;
  /** The PSP reference of the payment. */
  pspReference?: string;
  /** The HTTP response status. */
  status?: number;
}

export class ServiceError extends ApiError<Service> {}
