/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountTypeEnum
 */
export enum AccountTypeEnum {
  NotApplicable = 'notApplicable',
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for AccountTypeEnum
 */
export const accountTypeEnumSchema: Schema<AccountTypeEnum> = stringEnum(AccountTypeEnum);
