/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AcctTypeEnum
 */
export enum AcctTypeEnum {
  Enum01 = '01',
  Enum02 = '02',
  Enum03 = '03',
}

/**
 * Schema for AcctTypeEnum
 */
export const acctTypeEnumSchema: Schema<AcctTypeEnum> = stringEnum(AcctTypeEnum);
