/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface AdditionalDataOpi {
  /**
   * Optional boolean indicator. Set to **true** if you want an ecommerce transaction to return an `opi.transToken` as additional data in the response.
   * You can store this Oracle Payment Interface token in your Oracle Opera database. For more information and required settings, see [Oracle Opera](https://docs.adyen.com/plugins/oracle-opera#opi-token-ecommerce).
   */
  opiIncludeTransToken?: string;
}

export const additionalDataOpiSchema: Schema<AdditionalDataOpi> = object({
  opiIncludeTransToken: ['opi.includeTransToken', optional(string())],
});
