/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface AdditionalDataRatepay {
  /** Amount the customer has to pay each month. */
  ratepayInstallmentAmount?: string;
  /** Interest rate of this installment. */
  ratepayInterestRate?: string;
  /** Amount of the last installment. */
  ratepayLastInstallmentAmount?: string;
  /** Calendar day of the first payment. */
  ratepayPaymentFirstday?: string;
  /** Date the merchant delivered the goods to the customer. */
  ratepaydataDeliveryDate?: string;
  /** Date by which the customer must settle the payment. */
  ratepaydataDueDate?: string;
  /** Invoice date, defined by the merchant. If not included, the invoice date is set to the delivery date. */
  ratepaydataInvoiceDate?: string;
  /** Identification name or number for the invoice, defined by the merchant. */
  ratepaydataInvoiceId?: string;
}

export const additionalDataRatepaySchema: Schema<AdditionalDataRatepay> = object(
  {
    ratepayInstallmentAmount: ['ratepay.installmentAmount', optional(string())],
    ratepayInterestRate: ['ratepay.interestRate', optional(string())],
    ratepayLastInstallmentAmount: [
      'ratepay.lastInstallmentAmount',
      optional(string()),
    ],
    ratepayPaymentFirstday: ['ratepay.paymentFirstday', optional(string())],
    ratepaydataDeliveryDate: ['ratepaydata.deliveryDate', optional(string())],
    ratepaydataDueDate: ['ratepaydata.dueDate', optional(string())],
    ratepaydataInvoiceDate: ['ratepaydata.invoiceDate', optional(string())],
    ratepaydataInvoiceId: ['ratepaydata.invoiceId', optional(string())],
  }
);
