/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface AdditionalDataCarRental {
  /**
   * Pick-up date.
   * * Date format: `yyyyMMdd`
   */
  carRentalCheckOutDate?: string;
  /**
   * The customer service phone number of the car rental company.
   * * Format: Alphanumeric
   * * maxLength: 17
   */
  carRentalCustomerServiceTollFreeNumber?: string;
  /**
   * Number of days for which the car is being rented.
   * * Format: Numeric
   * * maxLength: 19
   */
  carRentalDaysRented?: string;
  /**
   * Any fuel charges associated with the rental.
   * * Format: Numeric
   * * maxLength: 12
   */
  carRentalFuelCharges?: string;
  /**
   * Any insurance charges associated with the rental.
   * * Format: Numeric
   * * maxLength: 12
   */
  carRentalInsuranceCharges?: string;
  /**
   * The city from which the car is rented.
   * * Format: Alphanumeric
   * * maxLength: 18
   */
  carRentalLocationCity?: string;
  /**
   * The country from which the car is rented.
   * * Format: Alphanumeric
   * * maxLength: 2
   */
  carRentalLocationCountry?: string;
  /**
   * The state or province from where the car is rented.
   * * Format: Alphanumeric
   * * maxLength: 3
   */
  carRentalLocationStateProvince?: string;
  /**
   * Indicates if the customer was a "no-show" (neither keeps nor cancels their booking).
   * * Y - Customer was a no show.
   * * N - Not applicable.
   */
  carRentalNoShowIndicator?: string;
  /** Charge associated with not returning a vehicle to the original rental location. */
  carRentalOneWayDropOffCharges?: string;
  /**
   * Daily rental rate.
   * * Format: Alphanumeric
   * * maxLength: 12
   */
  carRentalRate?: string;
  /**
   * Specifies whether the given rate is applied daily or weekly.
   * * D - Daily rate.
   * * W - Weekly rate.
   */
  carRentalRateIndicator?: string;
  /**
   * The rental agreement number associated with this car rental.
   * * Format: Alphanumeric
   * * maxLength: 9
   */
  carRentalRentalAgreementNumber?: string;
  /**
   * Daily rental rate.
   * * Format: Alphanumeric
   * * maxLength: 12
   */
  carRentalRentalClassId?: string;
  /**
   * The name of the person renting the car.
   * * Format: Alphanumeric
   * * maxLength: 26
   */
  carRentalRenterName?: string;
  /**
   * The city where the car must be returned.
   * * Format: Alphanumeric
   * * maxLength: 18
   */
  carRentalReturnCity?: string;
  /**
   * The country where the car must be returned.
   * * Format: Alphanumeric
   * * maxLength: 2
   */
  carRentalReturnCountry?: string;
  /**
   * The last date to return the car by.
   * * Date format: `yyyyMMdd`
   */
  carRentalReturnDate?: string;
  /**
   * Agency code, phone number, or address abbreviation
   * * Format: Alphanumeric
   * * maxLength: 10
   */
  carRentalReturnLocationId?: string;
  /**
   * The state or province where the car must be returned.
   * * Format: Alphanumeric
   * * maxLength: 3
   */
  carRentalReturnStateProvince?: string;
  /**
   * Indicates whether the goods or services were tax-exempt, or tax was not collected.
   * Values:
   * * Y - Goods or services were tax exempt
   * * N - Tax was not collected
   */
  carRentalTaxExemptIndicator?: string;
  /**
   * Number of nights.  This should be included in the auth message.
   * * Format: Numeric
   * * maxLength: 2
   */
  travelEntertainmentAuthDataDuration?: string;
  /**
   * Indicates what market-specific dataset will be submitted or is being submitted. Value should be "A" for Car rental. This should be included in the auth message.
   * * Format: Alphanumeric
   * * maxLength: 1
   */
  travelEntertainmentAuthDataMarket?: string;
}

export const additionalDataCarRentalSchema: Schema<AdditionalDataCarRental> = object(
  {
    carRentalCheckOutDate: ['carRental.checkOutDate', optional(string())],
    carRentalCustomerServiceTollFreeNumber: [
      'carRental.customerServiceTollFreeNumber',
      optional(string()),
    ],
    carRentalDaysRented: ['carRental.daysRented', optional(string())],
    carRentalFuelCharges: ['carRental.fuelCharges', optional(string())],
    carRentalInsuranceCharges: [
      'carRental.insuranceCharges',
      optional(string()),
    ],
    carRentalLocationCity: ['carRental.locationCity', optional(string())],
    carRentalLocationCountry: ['carRental.locationCountry', optional(string())],
    carRentalLocationStateProvince: [
      'carRental.locationStateProvince',
      optional(string()),
    ],
    carRentalNoShowIndicator: ['carRental.noShowIndicator', optional(string())],
    carRentalOneWayDropOffCharges: [
      'carRental.oneWayDropOffCharges',
      optional(string()),
    ],
    carRentalRate: ['carRental.rate', optional(string())],
    carRentalRateIndicator: ['carRental.rateIndicator', optional(string())],
    carRentalRentalAgreementNumber: [
      'carRental.rentalAgreementNumber',
      optional(string()),
    ],
    carRentalRentalClassId: ['carRental.rentalClassId', optional(string())],
    carRentalRenterName: ['carRental.renterName', optional(string())],
    carRentalReturnCity: ['carRental.returnCity', optional(string())],
    carRentalReturnCountry: ['carRental.returnCountry', optional(string())],
    carRentalReturnDate: ['carRental.returnDate', optional(string())],
    carRentalReturnLocationId: [
      'carRental.returnLocationId',
      optional(string()),
    ],
    carRentalReturnStateProvince: [
      'carRental.returnStateProvince',
      optional(string()),
    ],
    carRentalTaxExemptIndicator: [
      'carRental.taxExemptIndicator',
      optional(string()),
    ],
    travelEntertainmentAuthDataDuration: [
      'travelEntertainmentAuthData.duration',
      optional(string()),
    ],
    travelEntertainmentAuthDataMarket: [
      'travelEntertainmentAuthData.market',
      optional(string()),
    ],
  }
);
