/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface AdditionalDataLevel23 {
  /**
   * Customer code, if supplied by a customer.
   * Encoding: ASCII.
   * Max length: 25 characters.
   * > Required for Level 2 and Level 3 data.
   */
  enhancedSchemeDataCustomerReference?: string;
  /**
   * Destination country code.
   * Encoding: ASCII.
   * Max length: 3 characters.
   */
  enhancedSchemeDataDestinationCountryCode?: string;
  /**
   * The postal code of a destination address.
   * Encoding: ASCII.
   * Max length: 10 characters.
   * > Required for American Express.
   */
  enhancedSchemeDataDestinationPostalCode?: string;
  /**
   * Destination state or province code.
   * Encoding: ASCII.Max length: 3 characters.
   */
  enhancedSchemeDataDestinationStateProvinceCode?: string;
  /**
   * Duty amount, in minor units.
   * For example, 2000 means USD 20.00.
   * Max length: 12 characters.
   */
  enhancedSchemeDataDutyAmount?: string;
  /**
   * Shipping amount, in minor units.
   * For example, 2000 means USD 20.00.
   * Max length: 12 characters.
   */
  enhancedSchemeDataFreightAmount?: string;
  /**
   * Item commodity code.
   * Encoding: ASCII.
   * Max length: 12 characters.
   */
  enhancedSchemeDataItemDetailLineItemNrCommodityCode?: string;
  /**
   * Item description.
   * Encoding: ASCII.
   * Max length: 26 characters.
   */
  enhancedSchemeDataItemDetailLineItemNrDescription?: string;
  /**
   * Discount amount, in minor units.
   * For example, 2000 means USD 20.00.
   * Max length: 12 characters.
   */
  enhancedSchemeDataItemDetailLineItemNrDiscountAmount?: string;
  /**
   * Product code.
   * Encoding: ASCII.
   * Max length: 12 characters.
   */
  enhancedSchemeDataItemDetailLineItemNrProductCode?: string;
  /**
   * Quantity, specified as an integer value.
   * Value must be greater than 0.
   * Max length: 12 characters.
   */
  enhancedSchemeDataItemDetailLineItemNrQuantity?: string;
  /**
   * Total amount, in minor units.
   * For example, 2000 means USD 20.00.
   * Max length: 12 characters.
   */
  enhancedSchemeDataItemDetailLineItemNrTotalAmount?: string;
  /**
   * Item unit of measurement.
   * Encoding: ASCII.
   * Max length: 3 characters.
   */
  enhancedSchemeDataItemDetailLineItemNrUnitOfMeasure?: string;
  /**
   * Unit price, specified in [minor units](https://docs.adyen.com/development-resources/currency-codes).
   * Max length: 12 characters.
   */
  enhancedSchemeDataItemDetailLineItemNrUnitPrice?: string;
  /**
   * Order date.
   * * Format: `ddMMyy`
   * Encoding: ASCII.
   * Max length: 6 characters.
   */
  enhancedSchemeDataOrderDate?: string;
  /**
   * The postal code of a "ship-from" address.
   * Encoding: ASCII.
   * Max length: 10 characters.
   */
  enhancedSchemeDataShipFromPostalCode?: string;
  /**
   * Total tax amount, in minor units.
   * For example, 2000 means USD 20.00.
   * Max length: 12 characters.
   * > Required for Level 2 and Level 3 data.
   */
  enhancedSchemeDataTotalTaxAmount?: string;
}

export const additionalDataLevel23Schema: Schema<AdditionalDataLevel23> = object(
  {
    enhancedSchemeDataCustomerReference: [
      'enhancedSchemeData.customerReference',
      optional(string()),
    ],
    enhancedSchemeDataDestinationCountryCode: [
      'enhancedSchemeData.destinationCountryCode',
      optional(string()),
    ],
    enhancedSchemeDataDestinationPostalCode: [
      'enhancedSchemeData.destinationPostalCode',
      optional(string()),
    ],
    enhancedSchemeDataDestinationStateProvinceCode: [
      'enhancedSchemeData.destinationStateProvinceCode',
      optional(string()),
    ],
    enhancedSchemeDataDutyAmount: [
      'enhancedSchemeData.dutyAmount',
      optional(string()),
    ],
    enhancedSchemeDataFreightAmount: [
      'enhancedSchemeData.freightAmount',
      optional(string()),
    ],
    enhancedSchemeDataItemDetailLineItemNrCommodityCode: [
      'enhancedSchemeData.itemDetailLine[itemNr].commodityCode',
      optional(string()),
    ],
    enhancedSchemeDataItemDetailLineItemNrDescription: [
      'enhancedSchemeData.itemDetailLine[itemNr].description',
      optional(string()),
    ],
    enhancedSchemeDataItemDetailLineItemNrDiscountAmount: [
      'enhancedSchemeData.itemDetailLine[itemNr].discountAmount',
      optional(string()),
    ],
    enhancedSchemeDataItemDetailLineItemNrProductCode: [
      'enhancedSchemeData.itemDetailLine[itemNr].productCode',
      optional(string()),
    ],
    enhancedSchemeDataItemDetailLineItemNrQuantity: [
      'enhancedSchemeData.itemDetailLine[itemNr].quantity',
      optional(string()),
    ],
    enhancedSchemeDataItemDetailLineItemNrTotalAmount: [
      'enhancedSchemeData.itemDetailLine[itemNr].totalAmount',
      optional(string()),
    ],
    enhancedSchemeDataItemDetailLineItemNrUnitOfMeasure: [
      'enhancedSchemeData.itemDetailLine[itemNr].unitOfMeasure',
      optional(string()),
    ],
    enhancedSchemeDataItemDetailLineItemNrUnitPrice: [
      'enhancedSchemeData.itemDetailLine[itemNr].unitPrice',
      optional(string()),
    ],
    enhancedSchemeDataOrderDate: [
      'enhancedSchemeData.orderDate',
      optional(string()),
    ],
    enhancedSchemeDataShipFromPostalCode: [
      'enhancedSchemeData.shipFromPostalCode',
      optional(string()),
    ],
    enhancedSchemeDataTotalTaxAmount: [
      'enhancedSchemeData.totalTaxAmount',
      optional(string()),
    ],
  }
);
