/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type3Enum, type3EnumSchema } from './type3Enum';

export interface AndroidPay {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** **androidpay** */
  type?: Type3Enum;
}

export const androidPaySchema: Schema<AndroidPay> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  type: ['type', optional(type3EnumSchema)],
});
