/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  FundingSourceEnum,
  fundingSourceEnumSchema,
} from './fundingSourceEnum';
import { Type4Enum, type4EnumSchema } from './type4Enum';

export interface ApplePay {
  /** The stringified and base64 encoded `paymentData` you retrieved from the Apple framework. */
  applePayToken: string;
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The funding source that should be used when multiple sources are available. For Brazilian combo cards, by default the funding source is credit. To use debit, set this value to **debit**. */
  fundingSource?: FundingSourceEnum;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  /** **applepay** */
  type?: Type4Enum;
}

export const applePaySchema: Schema<ApplePay> = object({
  applePayToken: ['applePayToken', string()],
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  fundingSource: ['fundingSource', optional(fundingSourceEnumSchema)],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  type: ['type', optional(type4EnumSchema)],
});
