/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AttemptAuthenticationEnum
 */
export enum AttemptAuthenticationEnum {
  Always = 'always',
  Never = 'never',
  PreferNo = 'preferNo',
}

/**
 * Schema for AttemptAuthenticationEnum
 */
export const attemptAuthenticationEnumSchema: Schema<AttemptAuthenticationEnum> = stringEnum(AttemptAuthenticationEnum);
