/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';
import { EnabledEnum, enabledEnumSchema } from './enabledEnum';

/** Describes the configuration for AVS ([Address Verification System](https://en.wikipedia.org/wiki/Address_Verification_System)). */
export interface Avs1 {
  /** Indicates whether the shopper is allowed to modify the billing address for the current payment request. */
  addressEditable?: boolean;
  /**
   * Specifies whether the shopper should enter their billing address during checkout.
   * Allowed values:
   * * yes — Perform AVS checks for every card payment.
   * * automatic — Perform AVS checks only when required to optimize the conversion rate.
   * * no — Do not perform AVS checks.
   */
  enabled?: EnabledEnum;
}

export const avs1Schema: Schema<Avs1> = object({
  addressEditable: ['addressEditable', optional(boolean())],
  enabled: ['enabled', optional(enabledEnumSchema)],
});
