/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type5Enum, type5EnumSchema } from './type5Enum';

export interface BACSDirectDebit {
  /** The bank account number (without separators). */
  bankAccountNumber?: string;
  /** The bank routing number of the account. */
  bankLocationId?: string;
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The name of the bank account holder. */
  holderName?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  /** **directdebit_GB** */
  type?: Type5Enum;
}

export const bACSDirectDebitSchema: Schema<BACSDirectDebit> = object({
  bankAccountNumber: ['bankAccountNumber', optional(string())],
  bankLocationId: ['bankLocationId', optional(string())],
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  holderName: ['holderName', optional(string())],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  type: ['type', optional(type5EnumSchema)],
});
