/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BehaviorEnum
 */
export enum BehaviorEnum {
  DeductAccordingToSplitRatio = 'deductAccordingToSplitRatio',
  DeductFromLiableAccount = 'deductFromLiableAccount',
  DeductFromOneBalanceAccount = 'deductFromOneBalanceAccount',
}

/**
 * Schema for BehaviorEnum
 */
export const behaviorEnumSchema: Schema<BehaviorEnum> = stringEnum(BehaviorEnum);
