/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BillingAddressEnum
 */
export enum BillingAddressEnum {
  Editable = 'editable',
  Hidden = 'hidden',
  ReadOnly = 'readOnly',
}

/**
 * Schema for BillingAddressEnum
 */
export const billingAddressEnumSchema: Schema<BillingAddressEnum> = stringEnum(BillingAddressEnum);
