/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type7Enum, type7EnumSchema } from './type7Enum';

export interface BLIK {
  /** BLIK code consisting of 6 digits. */
  blikCode?: string;
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  /** **blik** */
  type?: Type7Enum;
}

export const bLIKSchema: Schema<BLIK> = object({
  blikCode: ['blikCode', optional(string())],
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  type: ['type', optional(type7EnumSchema)],
});
