/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { CardBrandDetails, cardBrandDetailsSchema } from './cardBrandDetails';

export interface CardDetailsResponse {
  /** The list of brands identified for the card. */
  brands?: CardBrandDetails[];
}

export const cardDetailsResponseSchema: Schema<CardDetailsResponse> = object({
  brands: ['brands', optional(array(lazy(() => cardBrandDetailsSchema)))],
});
