/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardHolderNameEnum
 */
export enum CardHolderNameEnum {
  NONE = 'NONE',
  OPTIONAL = 'OPTIONAL',
  REQUIRED = 'REQUIRED',
}

/**
 * Schema for CardHolderNameEnum
 */
export const cardHolderNameEnumSchema: Schema<CardHolderNameEnum> = stringEnum(CardHolderNameEnum);
