/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface CardBrandDetails {
  /** Indicates if you support the card brand. */
  supported?: boolean;
  /** The name of the card brand. */
  type?: string;
}

export const cardBrandDetailsSchema: Schema<CardBrandDetails> = object({
  supported: ['supported', optional(boolean())],
  type: ['type', optional(string())],
});
