/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface CardDetailsRequest {
  /**
   * A minimum of the first 8 digits of the card number and a maximum of the full card number. 11 digits gives the best result.
   * You must be [fully PCI compliant](https://docs.adyen.com/development-resources/pci-dss-compliance-guide) to collect raw card data.
   */
  cardNumber: string;
  /**
   * The shopper country.
   * Format: [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
   * Example: NL or DE
   */
  countryCode?: string;
  /** The encrypted card number. */
  encryptedCardNumber?: string;
  /** The merchant account identifier, with which you want to process the transaction. */
  merchantAccount: string;
  /**
   * The card brands you support. This is the [`brands`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/paymentMethods__resParam_paymentMethods-brands) array from your [`/paymentMethods`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/paymentMethods) response.
   * If not included, our API uses the ones configured for your merchant account and, if provided, the country code.
   */
  supportedBrands?: string[];
}

export const cardDetailsRequestSchema: Schema<CardDetailsRequest> = object({
  cardNumber: ['cardNumber', string()],
  countryCode: ['countryCode', optional(string())],
  encryptedCardNumber: ['encryptedCardNumber', optional(string())],
  merchantAccount: ['merchantAccount', string()],
  supportedBrands: ['supportedBrands', optional(array(string()))],
});
