/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type9Enum, type9EnumSchema } from './type9Enum';

export interface Cellulant {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The Cellulant issuer. */
  issuer?: string;
  /** **Cellulant** */
  type?: Type9Enum;
}

export const cellulantSchema: Schema<Cellulant> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  issuer: ['issuer', optional(string())],
  type: ['type', optional(type9EnumSchema)],
});
