/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Channel3Enum
 */
export enum Channel3Enum {
  IOS = 'iOS',
  Android = 'Android',
  Web = 'Web',
}

/**
 * Schema for Channel3Enum
 */
export const channel3EnumSchema: Schema<Channel3Enum> = stringEnum(Channel3Enum);
