/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Channel2Enum
 */
export enum Channel2Enum {
  IOS = 'iOS',
  Android = 'Android',
  Web = 'Web',
}

/**
 * Schema for Channel2Enum
 */
export const channel2EnumSchema: Schema<Channel2Enum> = stringEnum(Channel2Enum);
