/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CheckoutAwaitAction {
  /** A value that must be submitted to the `/payments/details` endpoint to verify this payment. */
  paymentData?: string;
  /** Specifies the payment method. */
  paymentMethodType?: string;
  /** **await** */
  type: string;
  /** Specifies the URL to redirect to. */
  url?: string;
}

export const checkoutAwaitActionSchema: Schema<CheckoutAwaitAction> = object({
  paymentData: ['paymentData', optional(string())],
  paymentMethodType: ['paymentMethodType', optional(string())],
  type: ['type', string()],
  url: ['url', optional(string())],
});
