/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CheckoutCancelOrderResponse {
  /** A unique reference of the cancellation request. */
  pspReference: string;
  /**
   * The result of the cancellation request.
   * Possible values:
   * * **Received** – Indicates the cancellation has successfully been received by Adyen, and will be processed.
   */
  resultCode: string;
}

export const checkoutCancelOrderResponseSchema: Schema<CheckoutCancelOrderResponse> = object(
  {
    pspReference: ['pspReference', string()],
    resultCode: ['resultCode', string()],
  }
);
