/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** The order request object that contains a pspReference that represents the order and the matching encrypted order data. */
export interface CheckoutOrder5 {
  /** The encrypted order data. */
  orderData: string;
  /** The `pspReference` that belongs to the order. */
  pspReference: string;
}

export const checkoutOrder5Schema: Schema<CheckoutOrder5> = object({
  orderData: ['orderData', string()],
  pspReference: ['pspReference', string()],
});
