/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CheckoutQrCodeAction {
  /** Expiry time of the QR code. */
  expiresAt?: string;
  /** A value that must be submitted to the `/payments/details` endpoint to verify this payment. */
  paymentData?: string;
  /** Specifies the payment method. */
  paymentMethodType?: string;
  /** The contents of the QR code as a UTF8 string. */
  qrCodeData?: string;
  /** **qrCode** */
  type: string;
  /** Specifies the URL to redirect to. */
  url?: string;
}

export const checkoutQrCodeActionSchema: Schema<CheckoutQrCodeAction> = object({
  expiresAt: ['expiresAt', optional(string())],
  paymentData: ['paymentData', optional(string())],
  paymentMethodType: ['paymentMethodType', optional(string())],
  qrCodeData: ['qrCodeData', optional(string())],
  type: ['type', string()],
  url: ['url', optional(string())],
});
