/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string } from '../schema';

export interface CheckoutUtilityResponse {
  /** The list of origin keys for all requested domains. For each list item, the key is the domain and the value is the origin key. */
  originKeys?: Record<string, string>;
}

export const checkoutUtilityResponseSchema: Schema<CheckoutUtilityResponse> = object(
  { originKeys: ['originKeys', optional(dict(string()))] }
);
