/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { CheckoutOrder5, checkoutOrder5Schema } from './checkoutOrder5';

export interface CheckoutCancelOrderRequest {
  /** The merchant account identifier that orderData belongs to. */
  merchantAccount: string;
  /** The order request object that contains a pspReference that represents the order and the matching encrypted order data. */
  order: CheckoutOrder5;
}

export const checkoutCancelOrderRequestSchema: Schema<CheckoutCancelOrderRequest> = object(
  {
    merchantAccount: ['merchantAccount', string()],
    order: ['order', lazy(() => checkoutOrder5Schema)],
  }
);
