/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** The order information required for partial payments. */
export interface CheckoutOrder2 {
  /** The encrypted order data. */
  orderData: string;
  /** The `pspReference` that belongs to the order. */
  pspReference: string;
}

export const checkoutOrder2Schema: Schema<CheckoutOrder2> = object({
  orderData: ['orderData', string()],
  pspReference: ['pspReference', string()],
});
