/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CheckoutThreeDS2Action {
  /** A token needed to authorise a payment. */
  authorisationToken?: string;
  /** A value that must be submitted to the `/payments/details` endpoint to verify this payment. */
  paymentData?: string;
  /** Specifies the payment method. */
  paymentMethodType?: string;
  /** A subtype of the token. */
  subtype?: string;
  /** A token to pass to the 3DS2 Component to get the fingerprint. */
  token?: string;
  /** **threeDS2** */
  type: string;
  /** Specifies the URL to redirect to. */
  url?: string;
}

export const checkoutThreeDS2ActionSchema: Schema<CheckoutThreeDS2Action> = object(
  {
    authorisationToken: ['authorisationToken', optional(string())],
    paymentData: ['paymentData', optional(string())],
    paymentMethodType: ['paymentMethodType', optional(string())],
    subtype: ['subtype', optional(string())],
    token: ['token', optional(string())],
    type: ['type', string()],
    url: ['url', optional(string())],
  }
);
