/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string } from '../schema';

export interface CheckoutRedirectAction {
  /** When the redirect URL must be accessed via POST, use this data to post to the redirect URL. */
  data?: Record<string, string>;
  /** Specifies the HTTP method, for example GET or POST. */
  method?: string;
  /** Specifies the payment method. */
  paymentMethodType?: string;
  /** **redirect** */
  type: string;
  /** Specifies the URL to redirect to. */
  url?: string;
}

export const checkoutRedirectActionSchema: Schema<CheckoutRedirectAction> = object(
  {
    data: ['data', optional(dict(string()))],
    method: ['method', optional(string())],
    paymentMethodType: ['paymentMethodType', optional(string())],
    type: ['type', string()],
    url: ['url', optional(string())],
  }
);
