/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Amount11, amount11Schema } from './amount11';
import { Amount14, amount14Schema } from './amount14';

/** Contains updated information regarding the order in case order information was provided in the request. */
export interface CheckoutOrderResponse1 {
  /** The initial amount of the order. */
  amount?: Amount11;
  /** The expiry date for the order. */
  expiresAt?: string;
  /** The encrypted order data. */
  orderData?: string;
  /** The `pspReference` that belongs to the order. */
  pspReference: string;
  /** The merchant reference for the order. */
  reference?: string;
  /** The updated remaining amount. */
  remainingAmount?: Amount14;
}

export const checkoutOrderResponse1Schema: Schema<CheckoutOrderResponse1> = object(
  {
    amount: ['amount', optional(lazy(() => amount11Schema))],
    expiresAt: ['expiresAt', optional(string())],
    orderData: ['orderData', optional(string())],
    pspReference: ['pspReference', string()],
    reference: ['reference', optional(string())],
    remainingAmount: ['remainingAmount', optional(lazy(() => amount14Schema))],
  }
);
