/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface CheckoutUtilityRequest {
  /** The list of origin domains, for which origin keys are requested. */
  originDomains: string[];
}

export const checkoutUtilityRequestSchema: Schema<CheckoutUtilityRequest> = object(
  { originDomains: ['originDomains', array(string())] }
);
