/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CheckoutOrder {
  /** The encrypted order data. */
  orderData: string;
  /** The `pspReference` that belongs to the order. */
  pspReference: string;
}

export const checkoutOrderSchema: Schema<CheckoutOrder> = object({
  orderData: ['orderData', string()],
  pspReference: ['pspReference', string()],
});
