/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Avs1, avs1Schema } from './avs1';
import {
  CardHolderNameEnum,
  cardHolderNameEnumSchema,
} from './cardHolderNameEnum';
import {
  InstallmentsNumber2,
  installmentsNumber2Schema,
} from './installmentsNumber2';
import { ShopperInput2, shopperInput2Schema } from './shopperInput2';

/** Specify configurations to enable additional features. */
export interface Configuration1 {
  /** Describes the configuration for AVS ([Address Verification System](https://en.wikipedia.org/wiki/Address_Verification_System)). */
  avs?: Avs1;
  /**
   * Determines whether the cardholder name should be provided or not.
   * Permitted values:
   * * NONE
   * * OPTIONAL
   * * REQUIRED
   */
  cardHolderName?: CardHolderNameEnum;
  /** Describes the configuration for [installment payments](https://docs.adyen.com/payment-methods/cards/credit-card-installments). */
  installments?: InstallmentsNumber2;
  /** Determines how to display the details fields. */
  shopperInput?: ShopperInput2;
}

export const configuration1Schema: Schema<Configuration1> = object({
  avs: ['avs', optional(lazy(() => avs1Schema))],
  cardHolderName: ['cardHolderName', optional(cardHolderNameEnumSchema)],
  installments: [
    'installments',
    optional(lazy(() => installmentsNumber2Schema)),
  ],
  shopperInput: ['shopperInput', optional(lazy(() => shopperInput2Schema))],
});
