/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CreateStandalonePaymentCancelRequest {
  /** The merchant account that is used to process the payment. */
  merchantAccount: string;
  /** The [`reference`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_reference) of the payment that you want to cancel. */
  paymentReference: string;
  /** Your reference for the cancel request. Maximum length: 80 characters. */
  reference?: string;
}

export const createStandalonePaymentCancelRequestSchema: Schema<CreateStandalonePaymentCancelRequest> = object(
  {
    merchantAccount: ['merchantAccount', string()],
    paymentReference: ['paymentReference', string()],
    reference: ['reference', optional(string())],
  }
);
