/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateApplePaySessionRequest {
  /**
   * This is the name that your shoppers will see in the Apple Pay interface.
   * The value returned as `configuration.merchantName` field from the [`/paymentMethods`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/paymentMethods) response.
   */
  displayName: string;
  /**
   * The domain name you provided when you added Apple Pay in your Customer Area.
   * This must match the `window.location.hostname` of the web shop.
   */
  domainName: string;
  /**
   * Your merchant identifier registered with Apple Pay.
   * Use the value of the `configuration.merchantId` field from the [`/paymentMethods`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/paymentMethods) response.
   */
  merchantIdentifier: string;
}

export const createApplePaySessionRequestSchema: Schema<CreateApplePaySessionRequest> = object(
  {
    displayName: ['displayName', string()],
    domainName: ['domainName', string()],
    merchantIdentifier: ['merchantIdentifier', string()],
  }
);
