/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { AccountInfo1, accountInfo1Schema } from './accountInfo1';
import { Address2, address2Schema } from './address2';
import { Address3, address3Schema } from './address3';
import { Amount1, amount1Schema } from './amount1';
import { Amount19, amount19Schema } from './amount19';
import { ApplicationInfo1, applicationInfo1Schema } from './applicationInfo1';
import {
  AuthenticationData1,
  authenticationData1Schema,
} from './authenticationData1';
import { ChannelEnum, channelEnumSchema } from './channelEnum';
import {
  CheckoutSessionInstallmentOption,
  checkoutSessionInstallmentOptionSchema,
} from './checkoutSessionInstallmentOption';
import { Company1, company1Schema } from './company1';
import { FundOrigin1, fundOrigin1Schema } from './fundOrigin1';
import { FundRecipient1, fundRecipient1Schema } from './fundRecipient1';
import { LineItem, lineItemSchema } from './lineItem';
import { Mandate1, mandate1Schema } from './mandate1';
import { ModeEnum, modeEnumSchema } from './modeEnum';
import { Name3, name3Schema } from './name3';
import {
  RecurringProcessingModel1Enum,
  recurringProcessingModel1EnumSchema,
} from './recurringProcessingModel1Enum';
import { RiskData1, riskData1Schema } from './riskData1';
import {
  ShopperInteractionEnum,
  shopperInteractionEnumSchema,
} from './shopperInteractionEnum';
import { Split, splitSchema } from './split';
import {
  StorePaymentMethodModeEnum,
  storePaymentMethodModeEnumSchema,
} from './storePaymentMethodModeEnum';
import {
  ThreeDSecureData1,
  threeDSecureData1Schema,
} from './threeDSecureData1';

export interface CreateCheckoutSessionResponse {
  /**
   * Shopper account information for 3D Secure 2.
   * > For 3D Secure 2 transactions, we recommend that you include this object to increase the chances of achieving a frictionless flow.
   */
  accountInfo?: AccountInfo1;
  /**
   * If you want a [BIN or card verification](https://docs.adyen.com/payment-methods/cards/bin-data-and-card-verification) request to use a non-zero value, assign this value to `additionalAmount` (while the amount must be still set to 0 to trigger BIN or card verification).
   * Required to be in the same currency as the `amount`.
   */
  additionalAmount?: Amount1;
  /**
   * This field contains additional data, which may be required for a particular payment request.
   * The `additionalData` object consists of entries, each of which includes the key and value.
   */
  additionalData?: Record<string, string>;
  /**
   * List of payment methods to be presented to the shopper. To refer to payment methods, use their `paymentMethod.type`from [Payment methods overview](https://docs.adyen.com/payment-methods).
   * Example: `"allowedPaymentMethods":["ideal","giropay"]`
   */
  allowedPaymentMethods?: string[];
  /** The amount of the payment. */
  amount: Amount19;
  /** Information about your application. For more details, see [Building Adyen solutions](https://docs.adyen.com/development-resources/building-adyen-solutions). */
  applicationInfo?: ApplicationInfo1;
  /** Configuration data for 3DS payments. */
  authenticationData?: AuthenticationData1;
  /** The address where to send the invoice. */
  billingAddress?: Address3;
  /**
   * List of payment methods to be hidden from the shopper. To refer to payment methods, use their `paymentMethod.type`from [Payment methods overview](https://docs.adyen.com/payment-methods).
   * Example: `"blockedPaymentMethods":["ideal","giropay"]`
   */
  blockedPaymentMethods?: string[];
  /** The delay between the authorisation and scheduled auto-capture, specified in hours. */
  captureDelayHours?: number;
  /**
   * The platform where a payment transaction takes place. This field is optional for filtering out payment methods that are only available on specific platforms. If this value is not set, then we will try to infer it from the `sdkVersion` or `token`.
   * Possible values:
   * * **iOS**
   * * **Android**
   * * **Web**
   */
  channel?: ChannelEnum;
  /** Information regarding the company. */
  company?: Company1;
  /** The shopper's two-letter country code. */
  countryCode?: string;
  /**
   * The shopper's date of birth.
   * Format [ISO-8601](https://www.w3.org/TR/NOTE-datetime): YYYY-MM-DD
   */
  dateOfBirth?: string;
  /**
   * The date and time when the purchased goods should be delivered.
   * [ISO 8601](https://www.w3.org/TR/NOTE-datetime) format: YYYY-MM-DDThh:mm:ss+TZD, for example, **2020-12-18T10:15:30+01:00**.
   */
  deliverAt?: string;
  /** The address where the purchased goods should be delivered. */
  deliveryAddress?: Address2;
  /** When true and `shopperReference` is provided, the shopper will be asked if the payment details should be stored for future one-click payments. */
  enableOneClick?: boolean;
  /** When true and `shopperReference` is provided, the payment details will be tokenized for payouts. */
  enablePayOut?: boolean;
  /** When true and `shopperReference` is provided, the payment details will be tokenized for recurring payments. */
  enableRecurring?: boolean;
  /** The date the session expires in [ISO8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. When not specified, the expiry date is set to 1 hour after session creation. You cannot set the session expiry to more than 24 hours after session creation. */
  expiresAt: string;
  /** The person or entity funding the money. */
  fundOrigin?: FundOrigin1;
  /** the person or entity receiving the money */
  fundRecipient?: FundRecipient1;
  /** A unique identifier of the session. */
  id: string;
  /** A set of key-value pairs that specifies the installment options available per payment method. The key must be a payment method name in lowercase. For example, **card** to specify installment options for all cards, or **visa** or **mc**. The value must be an object containing the installment options. */
  installmentOptions?: Record<string, CheckoutSessionInstallmentOption>;
  /**
   * Price and product information about the purchased items, to be included on the invoice sent to the shopper.
   * > This field is required for 3x 4x Oney, Affirm, Afterpay, Clearpay, Klarna, Ratepay, and Zip.
   */
  lineItems?: LineItem[];
  /** The mandate details to initiate recurring transaction. */
  mandate?: Mandate1;
  /** The [merchant category code](https://en.wikipedia.org/wiki/Merchant_category_code) (MCC) is a four-digit number, which relates to a particular market segment. This code reflects the predominant activity that is conducted by the merchant. */
  mcc?: string;
  /** The merchant account identifier, with which you want to process the transaction. */
  merchantAccount: string;
  /**
   * This reference allows linking multiple transactions to each other for reporting purposes (i.e. order auth-rate). The reference should be unique per billing cycle.
   * The same merchant order reference should never be reused after the first authorised attempt. If used, this field should be supplied for all incoming authorisations.
   * > We strongly recommend you send the `merchantOrderReference` value to benefit from linking payment requests when authorisation retries take place. In addition, we recommend you provide `retry.orderAttemptNumber`, `retry.chainAttemptNumber`, and `retry.skipRetry` values in `PaymentRequest.additionalData`.
   */
  merchantOrderReference?: string;
  /**
   * Metadata consists of entries, each of which includes a key and a value.
   * Limits:
   * * Maximum 20 key-value pairs per request.
   * * Maximum 20 characters per key.
   * * Maximum 80 characters per value.
   */
  metadata?: Record<string, string>;
  /**
   * Indicates the type of front end integration. Possible values:
   * * **embedded** (default): Drop-in or Components integration
   * * **hosted**: Hosted Checkout integration
   */
  mode?: ModeEnum;
  /** Authentication data produced by an MPI (Mastercard SecureCode, Visa Secure, or Cartes Bancaires). */
  mpiData?: ThreeDSecureData1;
  /** Date after which no further authorisations shall be performed. Only for 3D Secure 2. */
  recurringExpiry?: string;
  /** Minimum number of days between authorisations. Only for 3D Secure 2. */
  recurringFrequency?: string;
  /**
   * Defines a recurring payment type. Required when creating a token to store payment details.
   * Allowed values:
   * * `Subscription` – A transaction for a fixed or variable amount, which follows a fixed schedule.
   * * `CardOnFile` – With a card-on-file (CoF) transaction, card details are stored to enable one-click or omnichannel journeys, or simply to streamline the checkout process. Any subscription not following a fixed schedule is also considered a card-on-file transaction.
   * * `UnscheduledCardOnFile` – An unscheduled card-on-file (UCoF) transaction is a transaction that occurs on a non-fixed schedule and/or have variable amounts. For example, automatic top-ups when a cardholder's balance drops below a certain amount.
   */
  recurringProcessingModel?: RecurringProcessingModel1Enum;
  /** Specifies the redirect method (GET or POST) when redirecting back from the issuer. */
  redirectFromIssuerMethod?: string;
  /** Specifies the redirect method (GET or POST) when redirecting to the issuer. */
  redirectToIssuerMethod?: string;
  /** The reference to uniquely identify a payment. */
  reference: string;
  /** The URL to return to when a redirect payment is completed. */
  returnUrl: string;
  /** Any risk-related settings to apply to the payment. */
  riskData?: RiskData1;
  /** The payment session data you need to pass to your front end. */
  sessionData?: string;
  /** The shopper's email address. */
  shopperEmail?: string;
  /**
   * The shopper's IP address. In general, we recommend that you provide this data, as it is used in a number of risk checks (for instance, number of payment attempts or location-based checks).
   * > For 3D Secure 2 transactions, schemes require `shopperIP` for all browser-based implementations.
   * This field is also mandatory for some merchants depending on your business model. For more information, [contact Support](https://www.adyen.help/hc/en-us/requests/new).
   */
  shopperIP?: string;
  /**
   * Specifies the sales channel, through which the shopper gives their card details, and whether the shopper is a returning customer.
   * For the web service API, Adyen assumes Ecommerce shopper interaction by default.
   * This field has the following possible values:
   * * `Ecommerce` - Online transactions where the cardholder is present (online). For better authorisation rates, we recommend sending the card security code (CSC) along with the request.
   * * `ContAuth` - Card on file and/or subscription transactions, where the cardholder is known to the merchant (returning customer). If the shopper is present (online), you can supply also the CSC to improve authorisation (one-click payment).
   * * `Moto` - Mail-order and telephone-order transactions where the shopper is in contact with the merchant via email or telephone.
   * * `POS` - Point-of-sale transactions where the shopper is physically present to make a payment using a secure payment terminal.
   */
  shopperInteraction?: ShopperInteractionEnum;
  /** The combination of a language code and a country code to specify the language to be used in the payment. */
  shopperLocale?: string;
  /** The shopper's full name. This object is required for some payment methods such as AfterPay, Klarna, or if you're enrolled in the PayPal Seller Protection program. */
  shopperName?: Name3;
  /**
   * Your reference to uniquely identify this shopper, for example user ID or account ID. Minimum length: 3 characters.
   * > Your reference must not include personally identifiable information (PII), for example name or email address.
   */
  shopperReference?: string;
  /**
   * The text to be shown on the shopper's bank statement.
   *  We recommend sending a maximum of 22 characters, otherwise banks might truncate the string.
   *  Allowed characters: **a-z**, **A-Z**, **0-9**, spaces, and special characters **. , ' _ - ? + * /**.
   */
  shopperStatement?: string;
  /** The shopper's social security number. */
  socialSecurityNumber?: string;
  /** Boolean value indicating whether the card payment method should be split into separate debit and credit options. */
  splitCardFundingSources?: boolean;
  /** An array of objects specifying how the payment should be split when using [Adyen for Platforms](https://docs.adyen.com/platforms/processing-payments#providing-split-information) or [Issuing](https://docs.adyen.com/issuing/manage-funds#split). */
  splits?: Split[];
  /** The ecommerce or point-of-sale store that is processing the payment. */
  store?: string;
  /** When this is set to **true** and the `shopperReference` is provided, the payment details will be stored. */
  storePaymentMethod?: boolean;
  /**
   * Indicates if the details of the payment method will be stored for the shopper. Possible values:
   * * **disabled** – No details will be stored (default).
   * * **askForConsent** – If the `shopperReference` is provided, the UI lets the shopper choose if they want their payment details to be stored.
   * * **enabled** – If the `shopperReference` is provided, the details will be stored without asking the shopper for consent.
   */
  storePaymentMethodMode?: StorePaymentMethodModeEnum;
  /** The shopper's telephone number. */
  telephoneNumber?: string;
  /** If set to true, you will only perform the [3D Secure 2 authentication](https://docs.adyen.com/online-payments/3d-secure/other-3ds-flows/authentication-only), and not the payment authorisation. */
  threeDSAuthenticationOnly?: boolean;
  /** Set to true if the payment should be routed to a trusted MID. */
  trustedShopper?: boolean;
}

export const createCheckoutSessionResponseSchema: Schema<CreateCheckoutSessionResponse> = object(
  {
    accountInfo: ['accountInfo', optional(lazy(() => accountInfo1Schema))],
    additionalAmount: ['additionalAmount', optional(lazy(() => amount1Schema))],
    additionalData: ['additionalData', optional(dict(string()))],
    allowedPaymentMethods: ['allowedPaymentMethods', optional(array(string()))],
    amount: ['amount', lazy(() => amount19Schema)],
    applicationInfo: [
      'applicationInfo',
      optional(lazy(() => applicationInfo1Schema)),
    ],
    authenticationData: [
      'authenticationData',
      optional(lazy(() => authenticationData1Schema)),
    ],
    billingAddress: ['billingAddress', optional(lazy(() => address3Schema))],
    blockedPaymentMethods: ['blockedPaymentMethods', optional(array(string()))],
    captureDelayHours: ['captureDelayHours', optional(number())],
    channel: ['channel', optional(channelEnumSchema)],
    company: ['company', optional(lazy(() => company1Schema))],
    countryCode: ['countryCode', optional(string())],
    dateOfBirth: ['dateOfBirth', optional(string())],
    deliverAt: ['deliverAt', optional(string())],
    deliveryAddress: ['deliveryAddress', optional(lazy(() => address2Schema))],
    enableOneClick: ['enableOneClick', optional(boolean())],
    enablePayOut: ['enablePayOut', optional(boolean())],
    enableRecurring: ['enableRecurring', optional(boolean())],
    expiresAt: ['expiresAt', string()],
    fundOrigin: ['fundOrigin', optional(lazy(() => fundOrigin1Schema))],
    fundRecipient: [
      'fundRecipient',
      optional(lazy(() => fundRecipient1Schema)),
    ],
    id: ['id', string()],
    installmentOptions: [
      'installmentOptions',
      optional(dict(lazy(() => checkoutSessionInstallmentOptionSchema))),
    ],
    lineItems: ['lineItems', optional(array(lazy(() => lineItemSchema)))],
    mandate: ['mandate', optional(lazy(() => mandate1Schema))],
    mcc: ['mcc', optional(string())],
    merchantAccount: ['merchantAccount', string()],
    merchantOrderReference: ['merchantOrderReference', optional(string())],
    metadata: ['metadata', optional(dict(string()))],
    mode: ['mode', optional(modeEnumSchema)],
    mpiData: ['mpiData', optional(lazy(() => threeDSecureData1Schema))],
    recurringExpiry: ['recurringExpiry', optional(string())],
    recurringFrequency: ['recurringFrequency', optional(string())],
    recurringProcessingModel: [
      'recurringProcessingModel',
      optional(recurringProcessingModel1EnumSchema),
    ],
    redirectFromIssuerMethod: ['redirectFromIssuerMethod', optional(string())],
    redirectToIssuerMethod: ['redirectToIssuerMethod', optional(string())],
    reference: ['reference', string()],
    returnUrl: ['returnUrl', string()],
    riskData: ['riskData', optional(lazy(() => riskData1Schema))],
    sessionData: ['sessionData', optional(string())],
    shopperEmail: ['shopperEmail', optional(string())],
    shopperIP: ['shopperIP', optional(string())],
    shopperInteraction: [
      'shopperInteraction',
      optional(shopperInteractionEnumSchema),
    ],
    shopperLocale: ['shopperLocale', optional(string())],
    shopperName: ['shopperName', optional(lazy(() => name3Schema))],
    shopperReference: ['shopperReference', optional(string())],
    shopperStatement: ['shopperStatement', optional(string())],
    socialSecurityNumber: ['socialSecurityNumber', optional(string())],
    splitCardFundingSources: ['splitCardFundingSources', optional(boolean())],
    splits: ['splits', optional(array(lazy(() => splitSchema)))],
    store: ['store', optional(string())],
    storePaymentMethod: ['storePaymentMethod', optional(boolean())],
    storePaymentMethodMode: [
      'storePaymentMethodMode',
      optional(storePaymentMethodModeEnumSchema),
    ],
    telephoneNumber: ['telephoneNumber', optional(string())],
    threeDSAuthenticationOnly: [
      'threeDSAuthenticationOnly',
      optional(boolean()),
    ],
    trustedShopper: ['trustedShopper', optional(boolean())],
  }
);
