/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Amount25, amount25Schema } from './amount25';
import { LineItem, lineItemSchema } from './lineItem';
import {
  MerchantRefundReasonEnum,
  merchantRefundReasonEnumSchema,
} from './merchantRefundReasonEnum';
import { Split, splitSchema } from './split';

export interface CreatePaymentRefundRequest {
  /** The amount that you want to refund. The `currency` must match the currency used in authorisation, the `value` must be smaller than or equal to the authorised amount. */
  amount: Amount25;
  /**
   * Price and product information of the refunded items, required for [partial refunds](https://docs.adyen.com/online-payments/refund#refund-a-payment).
   * > This field is required for partial refunds with 3x 4x Oney, Affirm, Afterpay, Clearpay, Klarna, Ratepay, Zip and Atome.
   */
  lineItems?: LineItem[];
  /** The merchant account that is used to process the payment. */
  merchantAccount: string;
  /** Your reason for the refund request */
  merchantRefundReason?: MerchantRefundReasonEnum;
  /** Your reference for the refund request. Maximum length: 80 characters. */
  reference?: string;
  /** An array of objects specifying how the amount should be split between accounts when using Adyen for Platforms. For details, refer to [Providing split information](https://docs.adyen.com/marketplaces-and-platforms/processing-payments#providing-split-information). */
  splits?: Split[];
}

export const createPaymentRefundRequestSchema: Schema<CreatePaymentRefundRequest> = object(
  {
    amount: ['amount', lazy(() => amount25Schema)],
    lineItems: ['lineItems', optional(array(lazy(() => lineItemSchema)))],
    merchantAccount: ['merchantAccount', string()],
    merchantRefundReason: [
      'merchantRefundReason',
      optional(merchantRefundReasonEnumSchema),
    ],
    reference: ['reference', optional(string())],
    splits: ['splits', optional(array(lazy(() => splitSchema)))],
  }
);
