/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CreatePaymentReversalRequest {
  /** The merchant account that is used to process the payment. */
  merchantAccount: string;
  /** Your reference for the reversal request. Maximum length: 80 characters. */
  reference?: string;
}

export const createPaymentReversalRequestSchema: Schema<CreatePaymentReversalRequest> = object(
  {
    merchantAccount: ['merchantAccount', string()],
    reference: ['reference', optional(string())],
  }
);
