/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Amount22, amount22Schema } from './amount22';
import {
  IndustryUsage1Enum,
  industryUsage1EnumSchema,
} from './industryUsage1Enum';
import { Split, splitSchema } from './split';

export interface CreatePaymentAmountUpdateRequest {
  /** The updated amount. The `currency` must match the currency used in authorisation. */
  amount: Amount22;
  /**
   * The reason for the amount update. Possible values:
   * * **delayedCharge**
   * * **noShow**
   * * **installment**
   */
  industryUsage?: IndustryUsage1Enum;
  /** The merchant account that is used to process the payment. */
  merchantAccount: string;
  /** Your reference for the amount update request. Maximum length: 80 characters. */
  reference?: string;
  /** An array of objects specifying how the amount should be split between accounts when using Adyen for Platforms. For details, refer to [Providing split information](https://docs.adyen.com/marketplaces-and-platforms/processing-payments#providing-split-information). */
  splits?: Split[];
}

export const createPaymentAmountUpdateRequestSchema: Schema<CreatePaymentAmountUpdateRequest> = object(
  {
    amount: ['amount', lazy(() => amount22Schema)],
    industryUsage: ['industryUsage', optional(industryUsage1EnumSchema)],
    merchantAccount: ['merchantAccount', string()],
    reference: ['reference', optional(string())],
    splits: ['splits', optional(array(lazy(() => splitSchema)))],
  }
);
