/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DataOnlyEnum
 */
export enum DataOnlyEnum {
  False = 'false',
  True = 'true',
}

/**
 * Schema for DataOnlyEnum
 */
export const dataOnlyEnumSchema: Schema<DataOnlyEnum> = stringEnum(DataOnlyEnum);
