/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeliveryAddressIndicatorEnum
 */
export enum DeliveryAddressIndicatorEnum {
  ShipToBillingAddress = 'shipToBillingAddress',
  ShipToVerifiedAddress = 'shipToVerifiedAddress',
  ShipToNewAddress = 'shipToNewAddress',
  ShipToStore = 'shipToStore',
  DigitalGoods = 'digitalGoods',
  GoodsNotShipped = 'goodsNotShipped',
  Other = 'other',
}

/**
 * Schema for DeliveryAddressIndicatorEnum
 */
export const deliveryAddressIndicatorEnumSchema: Schema<DeliveryAddressIndicatorEnum> = stringEnum(DeliveryAddressIndicatorEnum);
