/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeliveryAddressEnum
 */
export enum DeliveryAddressEnum {
  Editable = 'editable',
  Hidden = 'hidden',
  ReadOnly = 'readOnly',
}

/**
 * Schema for DeliveryAddressEnum
 */
export const deliveryAddressEnumSchema: Schema<DeliveryAddressEnum> = stringEnum(DeliveryAddressEnum);
