/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema';
import {
  DetailsRequestAuthenticationData2,
  detailsRequestAuthenticationData2Schema,
} from './detailsRequestAuthenticationData2';
import {
  PaymentCompletionDetails2,
  paymentCompletionDetails2Schema,
} from './paymentCompletionDetails2';

export interface DetailsRequest {
  /** Data for 3DS authentication. */
  authenticationData?: DetailsRequestAuthenticationData2;
  /** Use this collection to submit the details that were returned as a result of the `/payments` call. */
  details: PaymentCompletionDetails2;
  /** The `paymentData` value from the `/payments` response. Required if the `/payments` response returns this value. */
  paymentData?: string;
  /** Change the `authenticationOnly` indicator originally set in the `/payments` request. Only needs to be set if you want to modify the value set previously. */
  threeDSAuthenticationOnly?: boolean;
}

export const detailsRequestSchema: Schema<DetailsRequest> = object({
  authenticationData: [
    'authenticationData',
    optional(lazy(() => detailsRequestAuthenticationData2Schema)),
  ],
  details: ['details', lazy(() => paymentCompletionDetails2Schema)],
  paymentData: ['paymentData', optional(string())],
  threeDSAuthenticationOnly: ['threeDSAuthenticationOnly', optional(boolean())],
});
