/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface DetailsRequestAuthenticationData {
  /**
   * If set to true, you will only perform the [3D Secure 2 authentication](https://docs.adyen.com/online-payments/3d-secure/other-3ds-flows/authentication-only), and not the payment authorisation.
   * Default: *false**.
   */
  authenticationOnly?: boolean;
}

export const detailsRequestAuthenticationDataSchema: Schema<DetailsRequestAuthenticationData> = object(
  { authenticationOnly: ['authenticationOnly', optional(boolean())] }
);
