/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DirectoryResponseEnum
 */
export enum DirectoryResponseEnum {
  A = 'A',
  C = 'C',
  D = 'D',
  I = 'I',
  N = 'N',
  R = 'R',
  U = 'U',
  Y = 'Y',
}

/**
 * Schema for DirectoryResponseEnum
 */
export const directoryResponseEnumSchema: Schema<DirectoryResponseEnum> = stringEnum(DirectoryResponseEnum);
