/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type12Enum, type12EnumSchema } from './type12Enum';

export interface Doku {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The shopper's first name. */
  firstName: string;
  /** The shopper's last name. */
  lastName: string;
  /** The shopper's email. */
  shopperEmail: string;
  /** **doku** */
  type: Type12Enum;
}

export const dokuSchema: Schema<Doku> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  shopperEmail: ['shopperEmail', string()],
  type: ['type', type12EnumSchema],
});
