/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type13Enum, type13EnumSchema } from './type13Enum';

export interface Dotpay {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The Dotpay issuer value of the shopper's selected bank. Set this to an **id** of a Dotpay issuer to preselect it. */
  issuer: string;
  /** **dotpay** */
  type?: Type13Enum;
}

export const dotpaySchema: Schema<Dotpay> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  issuer: ['issuer', string()],
  type: ['type', optional(type13EnumSchema)],
});
