/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type14Enum, type14EnumSchema } from './type14Enum';

export interface Dragonpay {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The Dragonpay issuer value of the shopper's selected bank. Set this to an **id** of a Dragonpay issuer to preselect it. */
  issuer: string;
  /** The shopper’s email address. */
  shopperEmail?: string;
  /** **dragonpay** */
  type: Type14Enum;
}

export const dragonpaySchema: Schema<Dragonpay> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  issuer: ['issuer', string()],
  shopperEmail: ['shopperEmail', optional(string())],
  type: ['type', type14EnumSchema],
});
