/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EnabledEnum
 */
export enum EnabledEnum {
  Yes = 'yes',
  No = 'no',
  Automatic = 'automatic',
}

/**
 * Schema for EnabledEnum
 */
export const enabledEnumSchema: Schema<EnabledEnum> = stringEnum(EnabledEnum);
