/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EntityTypeEnum
 */
export enum EntityTypeEnum {
  NaturalPerson = 'NaturalPerson',
  CompanyName = 'CompanyName',
}

/**
 * Schema for EntityTypeEnum
 */
export const entityTypeEnumSchema: Schema<EntityTypeEnum> = stringEnum(EntityTypeEnum);
