/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExemptionIndicatorEnum
 */
export enum ExemptionIndicatorEnum {
  LowValue = 'lowValue',
  SecureCorporate = 'secureCorporate',
  TrustedBeneficiary = 'trustedBeneficiary',
  TransactionRiskAnalysis = 'transactionRiskAnalysis',
}

/**
 * Schema for ExemptionIndicatorEnum
 */
export const exemptionIndicatorEnumSchema: Schema<ExemptionIndicatorEnum> = stringEnum(ExemptionIndicatorEnum);
