/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { Amount3, amount3Schema } from './amount3';
import { Amount4, amount4Schema } from './amount4';
import { Amount5, amount5Schema } from './amount5';
import { Amount6, amount6Schema } from './amount6';

/** The forex quote as returned in the response of the forex service. */
export interface ForexQuote2 {
  /** The account name. */
  account?: string;
  /** The account type. */
  accountType?: string;
  /** The base amount. */
  baseAmount?: Amount3;
  /** The base points. */
  basePoints: number;
  /** The buy rate. */
  buy?: Amount4;
  /** The interbank amount. */
  interbank?: Amount5;
  /** The reference assigned to the forex quote request. */
  reference?: string;
  /** The sell rate. */
  sell?: Amount6;
  /** The signature to validate the integrity. */
  signature?: string;
  /** The source of the forex quote. */
  source?: string;
  /** The type of forex. */
  type?: string;
  /** The date until which the forex quote is valid. */
  validTill: string;
}

export const forexQuote2Schema: Schema<ForexQuote2> = object({
  account: ['account', optional(string())],
  accountType: ['accountType', optional(string())],
  baseAmount: ['baseAmount', optional(lazy(() => amount3Schema))],
  basePoints: ['basePoints', number()],
  buy: ['buy', optional(lazy(() => amount4Schema))],
  interbank: ['interbank', optional(lazy(() => amount5Schema))],
  reference: ['reference', optional(string())],
  sell: ['sell', optional(lazy(() => amount6Schema))],
  signature: ['signature', optional(string())],
  source: ['source', optional(string())],
  type: ['type', optional(string())],
  validTill: ['validTill', string()],
});
