/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { FraudCheckResult, fraudCheckResultSchema } from './fraudCheckResult';

export interface FraudResult {
  /** The total fraud score generated by the risk checks. */
  accountScore: number;
  /** The result of the individual risk checks. */
  results?: FraudCheckResult[];
}

export const fraudResultSchema: Schema<FraudResult> = object({
  accountScore: ['accountScore', number()],
  results: ['results', optional(array(lazy(() => fraudCheckResultSchema)))],
});
