/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FraudResultTypeEnum
 */
export enum FraudResultTypeEnum {
  GREEN = 'GREEN',
  FRAUD = 'FRAUD',
}

/**
 * Schema for FraudResultTypeEnum
 */
export const fraudResultTypeEnumSchema: Schema<FraudResultTypeEnum> = stringEnum(FraudResultTypeEnum);
