/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FrequencyEnum
 */
export enum FrequencyEnum {
  Adhoc = 'adhoc',
  Daily = 'daily',
  Weekly = 'weekly',
  BiWeekly = 'biWeekly',
  Monthly = 'monthly',
  Quarterly = 'quarterly',
  HalfYearly = 'halfYearly',
  Yearly = 'yearly',
}

/**
 * Schema for FrequencyEnum
 */
export const frequencyEnumSchema: Schema<FrequencyEnum> = stringEnum(FrequencyEnum);
