/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FundingSourceEnum
 */
export enum FundingSourceEnum {
  Debit = 'debit',
}

/**
 * Schema for FundingSourceEnum
 */
export const fundingSourceEnumSchema: Schema<FundingSourceEnum> = stringEnum(FundingSourceEnum);
