/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type17Enum, type17EnumSchema } from './type17Enum';

export interface Giropay {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  /** **giropay** */
  type?: Type17Enum;
}

export const giropaySchema: Schema<Giropay> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  type: ['type', optional(type17EnumSchema)],
});
