/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IndustryUsageEnum
 */
export enum IndustryUsageEnum {
  NoShow = 'NoShow',
  DelayedCharge = 'DelayedCharge',
}

/**
 * Schema for IndustryUsageEnum
 */
export const industryUsageEnumSchema: Schema<IndustryUsageEnum> = stringEnum(IndustryUsageEnum);
