/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

/** Describes the configuration for [installment payments](https://docs.adyen.com/payment-methods/cards/credit-card-installments). */
export interface InstallmentsNumber2 {
  /** Maximum number of installments */
  maxNumberOfInstallments: number;
}

export const installmentsNumber2Schema: Schema<InstallmentsNumber2> = object({
  maxNumberOfInstallments: ['maxNumberOfInstallments', number()],
});
