/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { PlanEnum, planEnumSchema } from './planEnum';

/** Contains installment settings. For more information, refer to [Installments](https://docs.adyen.com/payment-methods/cards/credit-card-installments). */
export interface Installments2 {
  /**
   * The installment plan, used for [card installments in Japan](https://docs.adyen.com/payment-methods/cards/credit-card-installments#make-a-payment-japan). By default, this is set to **regular**. Possible values:
   * * **regular**
   * * **revolving**
   */
  plan?: PlanEnum;
  /**
   * Defines the number of installments. Its value needs to be greater than zero.
   * Usually, the maximum allowed number of installments is capped. For example, it may not be possible to split a payment in more than 24 installments. The acquirer sets this upper limit, so its value may vary.
   */
  value: number;
}

export const installments2Schema: Schema<Installments2> = object({
  plan: ['plan', optional(planEnumSchema)],
  value: ['value', number()],
});
