/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface LineItem {
  /** Item amount excluding the tax, in minor units. */
  amountExcludingTax?: number;
  /** Item amount including the tax, in minor units. */
  amountIncludingTax?: number;
  /** Brand of the item. */
  brand?: string;
  /** Color of the item. */
  color?: string;
  /** Description of the line item. */
  description?: string;
  /** ID of the line item. */
  id?: string;
  /** Link to the picture of the purchased item. */
  imageUrl?: string;
  /** Item category, used by the RatePay payment method. */
  itemCategory?: string;
  /** Manufacturer of the item. */
  manufacturer?: string;
  /** Link to the purchased item. */
  productUrl?: string;
  /** Number of items. */
  quantity?: number;
  /** Email associated with the given product in the basket (usually in electronic gift cards). */
  receiverEmail?: string;
  /** Size of the item. */
  size?: string;
  /** Stock keeping unit. */
  sku?: string;
  /** Tax amount, in minor units. */
  taxAmount?: number;
  /** Tax percentage, in minor units. */
  taxPercentage?: number;
  /** Universal Product Code. */
  upc?: string;
}

export const lineItemSchema: Schema<LineItem> = object({
  amountExcludingTax: ['amountExcludingTax', optional(number())],
  amountIncludingTax: ['amountIncludingTax', optional(number())],
  brand: ['brand', optional(string())],
  color: ['color', optional(string())],
  description: ['description', optional(string())],
  id: ['id', optional(string())],
  imageUrl: ['imageUrl', optional(string())],
  itemCategory: ['itemCategory', optional(string())],
  manufacturer: ['manufacturer', optional(string())],
  productUrl: ['productUrl', optional(string())],
  quantity: ['quantity', optional(number())],
  receiverEmail: ['receiverEmail', optional(string())],
  size: ['size', optional(string())],
  sku: ['sku', optional(string())],
  taxAmount: ['taxAmount', optional(number())],
  taxPercentage: ['taxPercentage', optional(number())],
  upc: ['upc', optional(string())],
});
