/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  StoredPaymentMethodResource,
  storedPaymentMethodResourceSchema,
} from './storedPaymentMethodResource';

export interface ListStoredPaymentMethodsResponse {
  /** Your merchant account. */
  merchantAccount?: string;
  /**
   * Your reference to uniquely identify this shopper, for example user ID or account ID. Minimum length: 3 characters.
   * > Your reference must not include personally identifiable information (PII), for example name or email address.
   */
  shopperReference?: string;
  /** List of all stored payment methods. */
  storedPaymentMethods?: StoredPaymentMethodResource[];
}

export const listStoredPaymentMethodsResponseSchema: Schema<ListStoredPaymentMethodsResponse> = object(
  {
    merchantAccount: ['merchantAccount', optional(string())],
    shopperReference: ['shopperReference', optional(string())],
    storedPaymentMethods: [
      'storedPaymentMethods',
      optional(array(lazy(() => storedPaymentMethodResourceSchema))),
    ],
  }
);
