/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  FundingSourceEnum,
  fundingSourceEnumSchema,
} from './fundingSourceEnum';
import { Type21Enum, type21EnumSchema } from './type21Enum';

export interface Masterpass {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The funding source that should be used when multiple sources are available. For Brazilian combo cards, by default the funding source is credit. To use debit, set this value to **debit**. */
  fundingSource?: FundingSourceEnum;
  /** The Masterpass transaction ID. */
  masterpassTransactionId: string;
  /** **masterpass** */
  type?: Type21Enum;
}

export const masterpassSchema: Schema<Masterpass> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  fundingSource: ['fundingSource', optional(fundingSourceEnumSchema)],
  masterpassTransactionId: ['masterpassTransactionId', string()],
  type: ['type', optional(type21EnumSchema)],
});
