/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type22Enum, type22EnumSchema } from './type22Enum';

export interface MBWay {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  shopperEmail: string;
  telephoneNumber: string;
  /** **mbway** */
  type?: Type22Enum;
}

export const mBWaySchema: Schema<MBWay> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  shopperEmail: ['shopperEmail', string()],
  telephoneNumber: ['telephoneNumber', string()],
  type: ['type', optional(type22EnumSchema)],
});
