/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Merchant device information. */
export interface MerchantDevice2 {
  /** Operating system running on the merchant device. */
  os?: string;
  /** Version of the operating system on the merchant device. */
  osVersion?: string;
  /** Merchant device reference. */
  reference?: string;
}

export const merchantDevice2Schema: Schema<MerchantDevice2> = object({
  os: ['os', optional(string())],
  osVersion: ['osVersion', optional(string())],
  reference: ['reference', optional(string())],
});
