/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MerchantRefundReason1Enum
 */
export enum MerchantRefundReason1Enum {
  FRAUD = 'FRAUD',
  EnumCUSTOMERREQUEST = 'CUSTOMER REQUEST',
  RETURN = 'RETURN',
  DUPLICATE = 'DUPLICATE',
  OTHER = 'OTHER',
}

/**
 * Schema for MerchantRefundReason1Enum
 */
export const merchantRefundReason1EnumSchema: Schema<MerchantRefundReason1Enum> = stringEnum(MerchantRefundReason1Enum);
