/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type23Enum, type23EnumSchema } from './type23Enum';

export interface MobilePay {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** **mobilepay** */
  type?: Type23Enum;
}

export const mobilePaySchema: Schema<MobilePay> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  type: ['type', optional(type23EnumSchema)],
});
