/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type24Enum, type24EnumSchema } from './type24Enum';

export interface MOLPay {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The shopper's bank. Specify this with the issuer value that corresponds to this bank. */
  issuer: string;
  /** **molpay** */
  type: Type24Enum;
}

export const mOLPaySchema: Schema<MOLPay> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  issuer: ['issuer', string()],
  type: ['type', type24EnumSchema],
});
