/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** The shopper's full name. */
export interface Name7 {
  /** The first name. */
  firstName: string;
  /** The last name. */
  lastName: string;
}

export const name7Schema: Schema<Name7> = object({
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
});
