/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** the name of the person */
export interface Name2 {
  /** The first name. */
  firstName: string;
  /** The last name. */
  lastName: string;
}

export const name2Schema: Schema<Name2> = object({
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
});
