/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Name {
  /** The first name. */
  firstName: string;
  /** The last name. */
  lastName: string;
}

export const nameSchema: Schema<Name> = object({
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
});
