/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NativeThreeDSEnum
 */
export enum NativeThreeDSEnum {
  Preferred = 'preferred',
}

/**
 * Schema for NativeThreeDSEnum
 */
export const nativeThreeDSEnumSchema: Schema<NativeThreeDSEnum> = stringEnum(NativeThreeDSEnum);
