/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface PaymentResponse4 {
  /** The card brand that the shopper used to pay. Only returned if `paymentMethod.type` is **scheme**. */
  brand?: string;
  /** The `paymentMethod.type` value used in the request. */
  type?: string;
}

export const paymentResponse4Schema: Schema<PaymentResponse4> = object({
  brand: ['brand', optional(string())],
  type: ['type', optional(string())],
});
