/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { RecurringDetail, recurringDetailSchema } from './recurringDetail';

export interface PaymentSetupResponse {
  /** The encoded payment session that you need to pass to the SDK. */
  paymentSession?: string;
  /** The detailed list of stored payment details required to generate payment forms. Will be empty if oneClick is set to false in the request. */
  recurringDetails?: RecurringDetail[];
}

export const paymentSetupResponseSchema: Schema<PaymentSetupResponse> = object({
  paymentSession: ['paymentSession', optional(string())],
  recurringDetails: [
    'recurringDetails',
    optional(array(lazy(() => recurringDetailSchema))),
  ],
});
