/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type27Enum, type27EnumSchema } from './type27Enum';

export interface PaymentDetails {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The payment method type. */
  type?: Type27Enum;
}

export const paymentDetailsSchema: Schema<PaymentDetails> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  type: ['type', optional(type27EnumSchema)],
});
