/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface PaymentMethodIssuer {
  /** A boolean value indicating whether this issuer is unavailable. Can be `true` whenever the issuer is offline. */
  disabled?: boolean;
  /** The unique identifier of this issuer, to submit in requests to /payments. */
  id: string;
  /** A localized name of the issuer. */
  name: string;
}

export const paymentMethodIssuerSchema: Schema<PaymentMethodIssuer> = object({
  disabled: ['disabled', optional(boolean())],
  id: ['id', string()],
  name: ['name', string()],
});
