/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PaymentVerificationRequest {
  /** Encrypted and signed payment result data. You should receive this value from the Checkout SDK after the shopper completes the payment. */
  payload: string;
}

export const paymentVerificationRequestSchema: Schema<PaymentVerificationRequest> = object(
  { payload: ['payload', string()] }
);
