/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { PaymentMethod, paymentMethodSchema } from './paymentMethod';
import {
  StoredPaymentMethod2,
  storedPaymentMethod2Schema,
} from './storedPaymentMethod2';

export interface PaymentMethodsResponse {
  /** Detailed list of payment methods required to generate payment forms. */
  paymentMethods?: PaymentMethod[];
  /** List of all stored payment methods. */
  storedPaymentMethods?: StoredPaymentMethod2[];
}

export const paymentMethodsResponseSchema: Schema<PaymentMethodsResponse> = object(
  {
    paymentMethods: [
      'paymentMethods',
      optional(array(lazy(() => paymentMethodSchema))),
    ],
    storedPaymentMethods: [
      'storedPaymentMethods',
      optional(array(lazy(() => storedPaymentMethod2Schema))),
    ],
  }
);
