/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface PaymentReversalResource {
  /** The merchant account that is used to process the payment. */
  merchantAccount: string;
  /** The [`pspReference`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__resParam_pspReference) of the payment to reverse. */
  paymentPspReference: string;
  /** Adyen's 16-character reference associated with the reversal request. */
  pspReference: string;
  /** Your reference for the reversal request. */
  reference?: string;
  /** The status of your request. This will always have the value **received**. */
  status: string;
}

export const paymentReversalResourceSchema: Schema<PaymentReversalResource> = object(
  {
    merchantAccount: ['merchantAccount', string()],
    paymentPspReference: ['paymentPspReference', string()],
    pspReference: ['pspReference', string()],
    reference: ['reference', optional(string())],
    status: ['status', string()],
  }
);
