/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { SubtypeEnum, subtypeEnumSchema } from './subtypeEnum';

export interface PayPal {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The unique ID associated with the order. */
  orderID?: string;
  /** The unique ID associated with the payer. */
  payerID?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  /** The type of flow to initiate. */
  subtype?: SubtypeEnum;
  /** **paypal** */
  type: string;
}

export const payPalSchema: Schema<PayPal> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  orderID: ['orderID', optional(string())],
  payerID: ['payerID', optional(string())],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  subtype: ['subtype', optional(subtypeEnumSchema)],
  type: ['type', string()],
});
