/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PersonalDetailsEnum
 */
export enum PersonalDetailsEnum {
  Editable = 'editable',
  Hidden = 'hidden',
  ReadOnly = 'readOnly',
}

/**
 * Schema for PersonalDetailsEnum
 */
export const personalDetailsEnumSchema: Schema<PersonalDetailsEnum> = stringEnum(PersonalDetailsEnum);
