/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Plan1Enum
 */
export enum Plan1Enum {
  Regular = 'regular',
  Revolving = 'revolving',
}

/**
 * Schema for Plan1Enum
 */
export const plan1EnumSchema: Schema<Plan1Enum> = stringEnum(Plan1Enum);
