/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PlanEnum
 */
export enum PlanEnum {
  Regular = 'regular',
  Revolving = 'revolving',
}

/**
 * Schema for PlanEnum
 */
export const planEnumSchema: Schema<PlanEnum> = stringEnum(PlanEnum);
