/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { BehaviorEnum, behaviorEnumSchema } from './behaviorEnum';

export interface PlatformChargebackLogic {
  behavior?: BehaviorEnum;
  targetAccount?: string;
}

export const platformChargebackLogicSchema: Schema<PlatformChargebackLogic> = object(
  {
    behavior: ['behavior', optional(behaviorEnumSchema)],
    targetAccount: ['targetAccount', optional(string())],
  }
);
