/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type28Enum, type28EnumSchema } from './type28Enum';

export interface Ratepay {
  /** The address where to send the invoice. */
  billingAddress?: string;
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The address where the goods should be delivered. */
  deliveryAddress?: string;
  /** Shopper name, date of birth, phone number, and email address. */
  personalDetails?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  /** **ratepay** */
  type: Type28Enum;
}

export const ratepaySchema: Schema<Ratepay> = object({
  billingAddress: ['billingAddress', optional(string())],
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  deliveryAddress: ['deliveryAddress', optional(string())],
  personalDetails: ['personalDetails', optional(string())],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  type: ['type', type28EnumSchema],
});
