/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RecurringProcessingModel3Enum
 */
export enum RecurringProcessingModel3Enum {
  CardOnFile = 'CardOnFile',
  Subscription = 'Subscription',
  UnscheduledCardOnFile = 'UnscheduledCardOnFile',
}

/**
 * Schema for RecurringProcessingModel3Enum
 */
export const recurringProcessingModel3EnumSchema: Schema<RecurringProcessingModel3Enum> = stringEnum(RecurringProcessingModel3Enum);
