/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RecurringProcessingModel7Enum
 */
export enum RecurringProcessingModel7Enum {
  CardOnFile = 'CardOnFile',
  Subscription = 'Subscription',
  UnscheduledCardOnFile = 'UnscheduledCardOnFile',
}

/**
 * Schema for RecurringProcessingModel7Enum
 */
export const recurringProcessingModel7EnumSchema: Schema<RecurringProcessingModel7Enum> = stringEnum(RecurringProcessingModel7Enum);
