/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RecurringProcessingModelEnum
 */
export enum RecurringProcessingModelEnum {
  CardOnFile = 'CardOnFile',
  Subscription = 'Subscription',
  UnscheduledCardOnFile = 'UnscheduledCardOnFile',
}

/**
 * Schema for RecurringProcessingModelEnum
 */
export const recurringProcessingModelEnumSchema: Schema<RecurringProcessingModelEnum> = stringEnum(RecurringProcessingModelEnum);
