/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RecurringProcessingModel1Enum
 */
export enum RecurringProcessingModel1Enum {
  CardOnFile = 'CardOnFile',
  Subscription = 'Subscription',
  UnscheduledCardOnFile = 'UnscheduledCardOnFile',
}

/**
 * Schema for RecurringProcessingModel1Enum
 */
export const recurringProcessingModel1EnumSchema: Schema<RecurringProcessingModel1Enum> = stringEnum(RecurringProcessingModel1Enum);
