/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ResponseAdditionalDataSepa {
  /**
   * The transaction signature date.
   * Format: yyyy-MM-dd
   */
  sepadirectdebitDateOfSignature?: string;
  /** Its value corresponds to the pspReference value of the transaction. */
  sepadirectdebitMandateId?: string;
  /**
   * This field can take one of the following values:
   * * OneOff: (OOFF) Direct debit instruction to initiate exactly one direct debit transaction.
   * * First: (FRST) Initial/first collection in a series of direct debit instructions.
   * * Recurring: (RCUR) Direct debit instruction to carry out regular direct debit transactions initiated by the creditor.
   * * Final: (FNAL) Last/final collection in a series of direct debit instructions.
   * Example: OOFF
   */
  sepadirectdebitSequenceType?: string;
}

export const responseAdditionalDataSepaSchema: Schema<ResponseAdditionalDataSepa> = object(
  {
    sepadirectdebitDateOfSignature: [
      'sepadirectdebit.dateOfSignature',
      optional(string()),
    ],
    sepadirectdebitMandateId: ['sepadirectdebit.mandateId', optional(string())],
    sepadirectdebitSequenceType: [
      'sepadirectdebit.sequenceType',
      optional(string()),
    ],
  }
);
