/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ResponseAdditionalDataInstallments {
  /** Type of installment. The value of `installmentType` should be **IssuerFinanced**. */
  installmentPaymentDataInstallmentType?: string;
  /** Annual interest rate. */
  installmentPaymentDataOptionItemNrAnnualPercentageRate?: string;
  /** First Installment Amount in minor units. */
  installmentPaymentDataOptionItemNrFirstInstallmentAmount?: string;
  /** Installment fee amount in minor units. */
  installmentPaymentDataOptionItemNrInstallmentFee?: string;
  /** Interest rate for the installment period. */
  installmentPaymentDataOptionItemNrInterestRate?: string;
  /** Maximum number of installments possible for this payment. */
  installmentPaymentDataOptionItemNrMaximumNumberOfInstallments?: string;
  /** Minimum number of installments possible for this payment. */
  installmentPaymentDataOptionItemNrMinimumNumberOfInstallments?: string;
  /** Total number of installments possible for this payment. */
  installmentPaymentDataOptionItemNrNumberOfInstallments?: string;
  /** Subsequent Installment Amount in minor units. */
  installmentPaymentDataOptionItemNrSubsequentInstallmentAmount?: string;
  /** Total amount in minor units. */
  installmentPaymentDataOptionItemNrTotalAmountDue?: string;
  /**
   * Possible values:
   * * PayInInstallmentsOnly
   * * PayInFullOnly
   * * PayInFullOrInstallments
   */
  installmentPaymentDataPaymentOptions?: string;
  /**
   * The number of installments that the payment amount should be charged with.
   * Example: 5
   * > Only relevant for card payments in countries that support installments.
   */
  installmentsValue?: string;
}

export const responseAdditionalDataInstallmentsSchema: Schema<ResponseAdditionalDataInstallments> = object(
  {
    installmentPaymentDataInstallmentType: [
      'installmentPaymentData.installmentType',
      optional(string()),
    ],
    installmentPaymentDataOptionItemNrAnnualPercentageRate: [
      'installmentPaymentData.option[itemNr].annualPercentageRate',
      optional(string()),
    ],
    installmentPaymentDataOptionItemNrFirstInstallmentAmount: [
      'installmentPaymentData.option[itemNr].firstInstallmentAmount',
      optional(string()),
    ],
    installmentPaymentDataOptionItemNrInstallmentFee: [
      'installmentPaymentData.option[itemNr].installmentFee',
      optional(string()),
    ],
    installmentPaymentDataOptionItemNrInterestRate: [
      'installmentPaymentData.option[itemNr].interestRate',
      optional(string()),
    ],
    installmentPaymentDataOptionItemNrMaximumNumberOfInstallments: [
      'installmentPaymentData.option[itemNr].maximumNumberOfInstallments',
      optional(string()),
    ],
    installmentPaymentDataOptionItemNrMinimumNumberOfInstallments: [
      'installmentPaymentData.option[itemNr].minimumNumberOfInstallments',
      optional(string()),
    ],
    installmentPaymentDataOptionItemNrNumberOfInstallments: [
      'installmentPaymentData.option[itemNr].numberOfInstallments',
      optional(string()),
    ],
    installmentPaymentDataOptionItemNrSubsequentInstallmentAmount: [
      'installmentPaymentData.option[itemNr].subsequentInstallmentAmount',
      optional(string()),
    ],
    installmentPaymentDataOptionItemNrTotalAmountDue: [
      'installmentPaymentData.option[itemNr].totalAmountDue',
      optional(string()),
    ],
    installmentPaymentDataPaymentOptions: [
      'installmentPaymentData.paymentOptions',
      optional(string()),
    ],
    installmentsValue: ['installments.value', optional(string())],
  }
);
