/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface ResponseAdditionalData3DSecure {
  /** Information provided by the issuer to the cardholder. If this field is present, you need to display this information to the cardholder. */
  cardHolderInfo?: string;
  /** The Cardholder Authentication Verification Value (CAVV) for the 3D Secure authentication session, as a Base64-encoded 20-byte array. */
  cavv?: string;
  /** The CAVV algorithm used. */
  cavvAlgorithm?: string;
  /**
   * Shows the [exemption type](https://docs.adyen.com/payments-fundamentals/psd2-sca-compliance-and-implementation-guide#specifypreferenceinyourapirequest) that Adyen requested for the payment.
   *  Possible values:
   * * **lowValue**
   * * **secureCorporate**
   * * **trustedBeneficiary**
   * * **transactionRiskAnalysis**
   */
  scaExemptionRequested?: string;
  /** Indicates whether a card is enrolled for 3D Secure 2. */
  threeds2CardEnrolled?: boolean;
}

export const responseAdditionalData3DSecureSchema: Schema<ResponseAdditionalData3DSecure> = object(
  {
    cardHolderInfo: ['cardHolderInfo', optional(string())],
    cavv: ['cavv', optional(string())],
    cavvAlgorithm: ['cavvAlgorithm', optional(string())],
    scaExemptionRequested: ['scaExemptionRequested', optional(string())],
    threeds2CardEnrolled: ['threeds2.cardEnrolled', optional(boolean())],
  }
);
