/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ResponseAdditionalDataOpi {
  /** Returned in the response if you included `opi.includeTransToken: true` in an ecommerce payment request. This contains an Oracle Payment Interface token that you can store in your Oracle Opera database to identify tokenized ecommerce transactions. For more information and required settings, see [Oracle Opera](https://docs.adyen.com/plugins/oracle-opera#opi-token-ecommerce). */
  opiTransToken?: string;
}

export const responseAdditionalDataOpiSchema: Schema<ResponseAdditionalDataOpi> = object(
  { opiTransToken: ['opi.transToken', optional(string())] }
);
