/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ResponseAdditionalDataBillingAddress {
  /** The billing address city passed in the payment request. */
  billingAddressCity?: string;
  /**
   * The billing address country passed in the payment request.
   * Example: NL
   */
  billingAddressCountry?: string;
  /** The billing address house number or name passed in the payment request. */
  billingAddressHouseNumberOrName?: string;
  /**
   * The billing address postal code passed in the payment request.
   * Example: 1011 DJ
   */
  billingAddressPostalCode?: string;
  /**
   * The billing address state or province passed in the payment request.
   * Example: NH
   */
  billingAddressStateOrProvince?: string;
  /** The billing address street passed in the payment request. */
  billingAddressStreet?: string;
}

export const responseAdditionalDataBillingAddressSchema: Schema<ResponseAdditionalDataBillingAddress> = object(
  {
    billingAddressCity: ['billingAddress.city', optional(string())],
    billingAddressCountry: ['billingAddress.country', optional(string())],
    billingAddressHouseNumberOrName: [
      'billingAddress.houseNumberOrName',
      optional(string()),
    ],
    billingAddressPostalCode: ['billingAddress.postalCode', optional(string())],
    billingAddressStateOrProvince: [
      'billingAddress.stateOrProvince',
      optional(string()),
    ],
    billingAddressStreet: ['billingAddress.street', optional(string())],
  }
);
