/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ResponseAdditionalDataNetworkTokens {
  /** Indicates whether a network token is available for the specified card. */
  networkTokenAvailable?: string;
  /** The Bank Identification Number of a tokenized card, which is the first six digits of a card number. */
  networkTokenBin?: string;
  /** The last four digits of a network token. */
  networkTokenTokenSummary?: string;
}

export const responseAdditionalDataNetworkTokensSchema: Schema<ResponseAdditionalDataNetworkTokens> = object(
  {
    networkTokenAvailable: ['networkToken.available', optional(string())],
    networkTokenBin: ['networkToken.bin', optional(string())],
    networkTokenTokenSummary: ['networkToken.tokenSummary', optional(string())],
  }
);
