/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResultCodeEnum
 */
export enum ResultCodeEnum {
  Success = 'Success',
  NotEnoughBalance = 'NotEnoughBalance',
  Failed = 'Failed',
}

/**
 * Schema for ResultCodeEnum
 */
export const resultCodeEnumSchema: Schema<ResultCodeEnum> = stringEnum(ResultCodeEnum);
