/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/**
 * The `sdkEphemPubKey` value as received from the 3D Secure 2 SDK.
 * Required for `deviceChannel` set to **app**.
 */
export interface SDKEphemPubKey2 {
  /** The `crv` value as received from the 3D Secure 2 SDK. */
  crv?: string;
  /** The `kty` value as received from the 3D Secure 2 SDK. */
  kty?: string;
  /** The `x` value as received from the 3D Secure 2 SDK. */
  x?: string;
  /** The `y` value as received from the 3D Secure 2 SDK. */
  y?: string;
}

export const sDKEphemPubKey2Schema: Schema<SDKEphemPubKey2> = object({
  crv: ['crv', optional(string())],
  kty: ['kty', optional(string())],
  x: ['x', optional(string())],
  y: ['y', optional(string())],
});
