/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SdkUiTypeEnum
 */
export enum SdkUiTypeEnum {
  MultiSelect = 'multiSelect',
  OtherHtml = 'otherHtml',
  OutOfBand = 'outOfBand',
  SingleSelect = 'singleSelect',
  Text = 'text',
}

/**
 * Schema for SdkUiTypeEnum
 */
export const sdkUiTypeEnumSchema: Schema<SdkUiTypeEnum> = stringEnum(SdkUiTypeEnum);
