/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type30Enum, type30EnumSchema } from './type30Enum';

export interface SEPADirectDebit {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The International Bank Account Number (IBAN). */
  iban: string;
  /** The name of the bank account holder. */
  ownerName: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  /** **sepadirectdebit** */
  type?: Type30Enum;
}

export const sEPADirectDebitSchema: Schema<SEPADirectDebit> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  iban: ['iban', string()],
  ownerName: ['ownerName', string()],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  type: ['type', optional(type30EnumSchema)],
});
