/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The type of the error. */
export interface ServiceError22 {
  errorCode?: string;
  errorType?: string;
  message?: string;
  pspReference?: string;
}

export const serviceError22Schema: Schema<ServiceError22> = object({
  errorCode: ['errorCode', optional(string())],
  errorType: ['errorType', optional(string())],
  message: ['message', optional(string())],
  pspReference: ['pspReference', optional(string())],
});
