/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ShopperInteractionEnum
 */
export enum ShopperInteractionEnum {
  Ecommerce = 'Ecommerce',
  ContAuth = 'ContAuth',
  Moto = 'Moto',
  POS = 'POS',
}

/**
 * Schema for ShopperInteractionEnum
 */
export const shopperInteractionEnumSchema: Schema<ShopperInteractionEnum> = stringEnum(ShopperInteractionEnum);
