/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Shopper interaction device, such as terminal, mobile device or web browser, to initiate payment requests. */
export interface ShopperInteractionDevice2 {
  /** Locale on the shopper interaction device. */
  locale?: string;
  /** Operating system running on the shopper interaction device. */
  os?: string;
  /** Version of the operating system on the shopper interaction device. */
  osVersion?: string;
}

export const shopperInteractionDevice2Schema: Schema<ShopperInteractionDevice2> = object(
  {
    locale: ['locale', optional(string())],
    os: ['os', optional(string())],
    osVersion: ['osVersion', optional(string())],
  }
);
