/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { SplitAmount2, splitAmount2Schema } from './splitAmount2';
import { Type10Enum, type10EnumSchema } from './type10Enum';

export interface Split {
  /** Unique identifier of the account where the split amount should be sent. This is required if `type` is **MarketPlace** or **BalanceAccount**. */
  account?: string;
  /** The amount of this split. */
  amount: SplitAmount2;
  /** A description of this split. */
  description?: string;
  /**
   * Your reference for the split, which you can use to link the split to other operations such as captures and refunds.
   * This is required if `type` is **MarketPlace** or **BalanceAccount**. For the other types, we also recommend sending a reference so you can reconcile the split and the associated payment in the transaction overview and in the reports. If the reference is not provided, the split is reported as part of the aggregated [TransferBalance record type](https://docs.adyen.com/reporting/marketpay-payments-accounting-report) in Adyen for Platforms.
   */
  reference?: string;
  /**
   * The type of split.
   * Possible values: **Default**, **PaymentFee**, **VAT**, **Commission**, **MarketPlace**, **BalanceAccount**, **Remainder**, **Surcharge**, **Tip**.
   */
  type: Type10Enum;
}

export const splitSchema: Schema<Split> = object({
  account: ['account', optional(string())],
  amount: ['amount', lazy(() => splitAmount2Schema)],
  description: ['description', optional(string())],
  reference: ['reference', optional(string())],
  type: ['type', type10EnumSchema],
});
