/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

/** The amount of this split. */
export interface SplitAmount2 {
  /**
   * The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes).
   * If this value is not provided, the currency in which the payment is made will be used.
   */
  currency?: string;
  /** The amount in [minor units](https://docs.adyen.com/development-resources/currency-codes). */
  value: bigint;
}

export const splitAmount2Schema: Schema<SplitAmount2> = object({
  currency: ['currency', optional(string())],
  value: ['value', bigint()],
});
