/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface StandalonePaymentCancelResource {
  /** The merchant account that is used to process the payment. */
  merchantAccount: string;
  /** The [`reference`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_reference) of the payment to cancel. */
  paymentReference: string;
  /** Adyen's 16-character reference associated with the cancel request. */
  pspReference: string;
  /** Your reference for the cancel request. */
  reference?: string;
  /** The status of your request. This will always have the value **received**. */
  status: string;
}

export const standalonePaymentCancelResourceSchema: Schema<StandalonePaymentCancelResource> = object(
  {
    merchantAccount: ['merchantAccount', string()],
    paymentReference: ['paymentReference', string()],
    pspReference: ['pspReference', string()],
    reference: ['reference', optional(string())],
    status: ['status', string()],
  }
);
