/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StorePaymentMethodModeEnum
 */
export enum StorePaymentMethodModeEnum {
  AskForConsent = 'askForConsent',
  Disabled = 'disabled',
  Enabled = 'enabled',
}

/**
 * Schema for StorePaymentMethodModeEnum
 */
export const storePaymentMethodModeEnumSchema: Schema<StorePaymentMethodModeEnum> = stringEnum(StorePaymentMethodModeEnum);
