/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { BankAccount1, bankAccount1Schema } from './bankAccount1';
import { Card3, card3Schema } from './card3';

/** Contains information on previously stored payment details. */
export interface StoredDetails2 {
  /** The stored bank account. */
  bank?: BankAccount1;
  /** The stored card information. */
  card?: Card3;
  /** The email associated with stored payment details. */
  emailAddress?: string;
}

export const storedDetails2Schema: Schema<StoredDetails2> = object({
  bank: ['bank', optional(lazy(() => bankAccount1Schema))],
  card: ['card', optional(lazy(() => card3Schema))],
  emailAddress: ['emailAddress', optional(string())],
});
