/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface SubMerchant {
  /**
   * The city of the sub-merchant's address.
   * * Format: Alphanumeric
   * * Maximum length: 13 characters
   */
  city?: string;
  /**
   * The three-letter country code of the sub-merchant's address. For example, **BRA** for Brazil.
   * * Format: [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)
   * * Fixed length: 3 characters
   */
  country?: string;
  /**
   * The sub-merchant's 4-digit Merchant Category Code (MCC).
   * * Format: Numeric
   * * Fixed length: 4 digits
   */
  mcc?: string;
  /**
   * The name of the sub-merchant. Based on scheme specifications, this value will overwrite the shopper statement  that will appear in the card statement.
   * * Format: Alphanumeric
   * * Maximum length: 22 characters
   */
  name?: string;
  /**
   * The tax ID of the sub-merchant.
   * * Format: Numeric
   * * Fixed length: 11 digits for the CPF or 14 digits for the CNPJ
   */
  taxId?: string;
}

export const subMerchantSchema: Schema<SubMerchant> = object({
  city: ['city', optional(string())],
  country: ['country', optional(string())],
  mcc: ['mcc', optional(string())],
  name: ['name', optional(string())],
  taxId: ['taxId', optional(string())],
});
