/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubtypeEnum
 */
export enum SubtypeEnum {
  Redirect = 'redirect',
  Sdk = 'sdk',
}

/**
 * Schema for SubtypeEnum
 */
export const subtypeEnumSchema: Schema<SubtypeEnum> = stringEnum(SubtypeEnum);
