/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ThreeDSVersionEnum
 */
export enum ThreeDSVersionEnum {
  Enum210 = '2.1.0',
  Enum220 = '2.2.0',
}

/**
 * Schema for ThreeDSVersionEnum
 */
export const threeDSVersionEnumSchema: Schema<ThreeDSVersionEnum> = stringEnum(ThreeDSVersionEnum);
