/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ThreeDS2ResponseData {
  acsChallengeMandated?: string;
  acsOperatorID?: string;
  acsReferenceNumber?: string;
  acsSignedContent?: string;
  acsTransID?: string;
  acsURL?: string;
  authenticationType?: string;
  cardHolderInfo?: string;
  cavvAlgorithm?: string;
  challengeIndicator?: string;
  dsReferenceNumber?: string;
  dsTransID?: string;
  exemptionIndicator?: string;
  messageVersion?: string;
  riskScore?: string;
  sdkEphemPubKey?: string;
  threeDSServerTransID?: string;
  transStatus?: string;
  transStatusReason?: string;
}

export const threeDS2ResponseDataSchema: Schema<ThreeDS2ResponseData> = object({
  acsChallengeMandated: ['acsChallengeMandated', optional(string())],
  acsOperatorID: ['acsOperatorID', optional(string())],
  acsReferenceNumber: ['acsReferenceNumber', optional(string())],
  acsSignedContent: ['acsSignedContent', optional(string())],
  acsTransID: ['acsTransID', optional(string())],
  acsURL: ['acsURL', optional(string())],
  authenticationType: ['authenticationType', optional(string())],
  cardHolderInfo: ['cardHolderInfo', optional(string())],
  cavvAlgorithm: ['cavvAlgorithm', optional(string())],
  challengeIndicator: ['challengeIndicator', optional(string())],
  dsReferenceNumber: ['dsReferenceNumber', optional(string())],
  dsTransID: ['dsTransID', optional(string())],
  exemptionIndicator: ['exemptionIndicator', optional(string())],
  messageVersion: ['messageVersion', optional(string())],
  riskScore: ['riskScore', optional(string())],
  sdkEphemPubKey: ['sdkEphemPubKey', optional(string())],
  threeDSServerTransID: ['threeDSServerTransID', optional(string())],
  transStatus: ['transStatus', optional(string())],
  transStatusReason: ['transStatusReason', optional(string())],
});
