/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  ThreeDSReqAuthMethodEnum,
  threeDSReqAuthMethodEnumSchema,
} from './threeDSReqAuthMethodEnum';

/** Information about how the 3DS Requestor authenticated the cardholder before or during the transaction */
export interface ThreeDSRequestorAuthenticationInfo2 {
  /** Data that documents and supports a specific authentication process. Maximum length: 2048 bytes. */
  threeDSReqAuthData?: string;
  /**
   * Mechanism used by the Cardholder to authenticate to the 3DS Requestor. Allowed values:
   * * **01** — No 3DS Requestor authentication occurred (for example, cardholder “logged in” as guest).
   * * **02** — Login to the cardholder account at the 3DS Requestor system using 3DS Requestor’s own credentials.
   * * **03** — Login to the cardholder account at the 3DS Requestor system using federated ID.
   * * **04** — Login to the cardholder account at the 3DS Requestor system using issuer credentials.
   * * **05** — Login to the cardholder account at the 3DS Requestor system using third-party authentication.
   * * **06** — Login to the cardholder account at the 3DS Requestor system using FIDO Authenticator.
   */
  threeDSReqAuthMethod?: ThreeDSReqAuthMethodEnum;
  /** Date and time in UTC of the cardholder authentication. Format: YYYYMMDDHHMM */
  threeDSReqAuthTimestamp?: string;
}

export const threeDSRequestorAuthenticationInfo2Schema: Schema<ThreeDSRequestorAuthenticationInfo2> = object(
  {
    threeDSReqAuthData: ['threeDSReqAuthData', optional(string())],
    threeDSReqAuthMethod: [
      'threeDSReqAuthMethod',
      optional(threeDSReqAuthMethodEnumSchema),
    ],
    threeDSReqAuthTimestamp: ['threeDSReqAuthTimestamp', optional(string())],
  }
);
