/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  AuthenticationResponseEnum,
  authenticationResponseEnumSchema,
} from './authenticationResponseEnum';
import {
  ChallengeCancelEnum,
  challengeCancelEnumSchema,
} from './challengeCancelEnum';
import {
  DirectoryResponseEnum,
  directoryResponseEnumSchema,
} from './directoryResponseEnum';

/** Authentication data produced by an MPI (Mastercard SecureCode, Visa Secure, or Cartes Bancaires). */
export interface ThreeDSecureData1 {
  /**
   * In 3D Secure 1, the authentication response if the shopper was redirected.
   * In 3D Secure 2, this is the `transStatus` from the challenge result. If the transaction was frictionless, omit this parameter.
   */
  authenticationResponse?: AuthenticationResponseEnum;
  /** The cardholder authentication value (base64 encoded, 20 bytes in a decoded form). */
  cavv?: string;
  /** The CAVV algorithm used. Include this only for 3D Secure 1. */
  cavvAlgorithm?: string;
  /** Indicator informing the Access Control Server (ACS) and the Directory Server (DS) that the authentication has been cancelled. For possible values, refer to [3D Secure API reference](https://docs.adyen.com/online-payments/3d-secure/api-reference#mpidata). */
  challengeCancel?: ChallengeCancelEnum;
  /**
   * In 3D Secure 1, this is the enrollment response from the 3D directory server.
   * In 3D Secure 2, this is the `transStatus` from the `ARes`.
   */
  directoryResponse?: DirectoryResponseEnum;
  /** Supported for 3D Secure 2. The unique transaction identifier assigned by the Directory Server (DS) to identify a single transaction. */
  dsTransID?: string;
  /** The electronic commerce indicator. */
  eci?: string;
  /** Risk score calculated by Directory Server (DS). Required for Cartes Bancaires integrations. */
  riskScore?: string;
  /** The version of the 3D Secure protocol. */
  threeDSVersion?: string;
  /** Network token authentication verification value (TAVV). The network token cryptogram. */
  tokenAuthenticationVerificationValue?: string;
  /** Provides information on why the `transStatus` field has the specified value. For possible values, refer to [our docs](https://docs.adyen.com/online-payments/3d-secure/api-reference#possible-transstatusreason-values). */
  transStatusReason?: string;
  /** Supported for 3D Secure 1. The transaction identifier (Base64-encoded, 20 bytes in a decoded form). */
  xid?: string;
}

export const threeDSecureData1Schema: Schema<ThreeDSecureData1> = object({
  authenticationResponse: [
    'authenticationResponse',
    optional(authenticationResponseEnumSchema),
  ],
  cavv: ['cavv', optional(string())],
  cavvAlgorithm: ['cavvAlgorithm', optional(string())],
  challengeCancel: ['challengeCancel', optional(challengeCancelEnumSchema)],
  directoryResponse: [
    'directoryResponse',
    optional(directoryResponseEnumSchema),
  ],
  dsTransID: ['dsTransID', optional(string())],
  eci: ['eci', optional(string())],
  riskScore: ['riskScore', optional(string())],
  threeDSVersion: ['threeDSVersion', optional(string())],
  tokenAuthenticationVerificationValue: [
    'tokenAuthenticationVerificationValue',
    optional(string()),
  ],
  transStatusReason: ['transStatusReason', optional(string())],
  xid: ['xid', optional(string())],
});
