/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionTypeEnum
 */
export enum TransactionTypeEnum {
  GoodsOrServicePurchase = 'goodsOrServicePurchase',
  CheckAcceptance = 'checkAcceptance',
  AccountFunding = 'accountFunding',
  QuasiCashTransaction = 'quasiCashTransaction',
  PrepaidActivationAndLoad = 'prepaidActivationAndLoad',
}

/**
 * Schema for TransactionTypeEnum
 */
export const transactionTypeEnumSchema: Schema<TransactionTypeEnum> = stringEnum(TransactionTypeEnum);
