/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransTypeEnum
 */
export enum TransTypeEnum {
  Enum01 = '01',
  Enum03 = '03',
  Enum10 = '10',
  Enum11 = '11',
  Enum28 = '28',
}

/**
 * Schema for TransTypeEnum
 */
export const transTypeEnumSchema: Schema<TransTypeEnum> = stringEnum(TransTypeEnum);
