/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type36Enum
 */
export enum Type36Enum {
  Zip = 'zip',
  ZipPos = 'zip_pos',
}

/**
 * Schema for Type36Enum
 */
export const type36EnumSchema: Schema<Type36Enum> = stringEnum(Type36Enum);
