/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type14Enum
 */
export enum Type14Enum {
  DragonpayEbanking = 'dragonpay_ebanking',
  DragonpayOtcBanking = 'dragonpay_otc_banking',
  DragonpayOtcNonBanking = 'dragonpay_otc_non_banking',
  DragonpayOtcPhilippines = 'dragonpay_otc_philippines',
}

/**
 * Schema for Type14Enum
 */
export const type14EnumSchema: Schema<Type14Enum> = stringEnum(Type14Enum);
