/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type20Enum
 */
export enum Type20Enum {
  Klarna = 'klarna',
  Klarnapayments = 'klarnapayments',
  KlarnapaymentsAccount = 'klarnapayments_account',
  KlarnapaymentsB2b = 'klarnapayments_b2b',
  KlarnaPaynow = 'klarna_paynow',
  KlarnaAccount = 'klarna_account',
  KlarnaB2b = 'klarna_b2b',
}

/**
 * Schema for Type20Enum
 */
export const type20EnumSchema: Schema<Type20Enum> = stringEnum(Type20Enum);
