/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type16Enum
 */
export enum Type16Enum {
  OnlineBankingPL = 'onlineBanking_PL',
  Eps = 'eps',
  OnlineBankingSK = 'onlineBanking_SK',
  OnlineBankingCZ = 'onlineBanking_CZ',
}

/**
 * Schema for Type16Enum
 */
export const type16EnumSchema: Schema<Type16Enum> = stringEnum(Type16Enum);
