/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type31Enum
 */
export enum Type31Enum {
  BcmcMobile = 'bcmc_mobile',
  BcmcMobileQR = 'bcmc_mobile_QR',
  BcmcMobileApp = 'bcmc_mobile_app',
  MomoWallet = 'momo_wallet',
  MomoWalletApp = 'momo_wallet_app',
  PaymayaWallet = 'paymaya_wallet',
  GrabpaySG = 'grabpay_SG',
  GrabpayMY = 'grabpay_MY',
  GrabpayTH = 'grabpay_TH',
  GrabpayID = 'grabpay_ID',
  GrabpayVN = 'grabpay_VN',
  GrabpayPH = 'grabpay_PH',
  Oxxo = 'oxxo',
  Gcash = 'gcash',
  Kakaopay = 'kakaopay',
  Truemoney = 'truemoney',
}

/**
 * Schema for Type31Enum
 */
export const type31EnumSchema: Schema<Type31Enum> = stringEnum(Type31Enum);
