/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type33Enum
 */
export enum Type33Enum {
  Visacheckout = 'visacheckout',
}

/**
 * Schema for Type33Enum
 */
export const type33EnumSchema: Schema<Type33Enum> = stringEnum(Type33Enum);
