/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type34Enum
 */
export enum Type34Enum {
  Wechatpay = 'wechatpay',
  WechatpayPos = 'wechatpay_pos',
}

/**
 * Schema for Type34Enum
 */
export const type34EnumSchema: Schema<Type34Enum> = stringEnum(Type34Enum);
