/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type32Enum
 */
export enum Type32Enum {
  Vipps = 'vipps',
}

/**
 * Schema for Type32Enum
 */
export const type32EnumSchema: Schema<Type32Enum> = stringEnum(Type32Enum);
