/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type12Enum
 */
export enum Type12Enum {
  DokuMandiriVa = 'doku_mandiri_va',
  DokuCimbVa = 'doku_cimb_va',
  DokuDanamonVa = 'doku_danamon_va',
  DokuBniVa = 'doku_bni_va',
  DokuPermataLiteAtm = 'doku_permata_lite_atm',
  DokuBriVa = 'doku_bri_va',
  DokuBcaVa = 'doku_bca_va',
  DokuAlfamart = 'doku_alfamart',
  DokuIndomaret = 'doku_indomaret',
}

/**
 * Schema for Type12Enum
 */
export const type12EnumSchema: Schema<Type12Enum> = stringEnum(Type12Enum);
