/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type18Enum
 */
export enum Type18Enum {
  Googlepay = 'googlepay',
}

/**
 * Schema for Type18Enum
 */
export const type18EnumSchema: Schema<Type18Enum> = stringEnum(Type18Enum);
