/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type6Enum
 */
export enum Type6Enum {
  BilldeskOnline = 'billdesk_online',
  BilldeskWallet = 'billdesk_wallet',
  OnlinebankingIN = 'onlinebanking_IN',
  WalletIN = 'wallet_IN',
}

/**
 * Schema for Type6Enum
 */
export const type6EnumSchema: Schema<Type6Enum> = stringEnum(Type6Enum);
