/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type17Enum
 */
export enum Type17Enum {
  Giropay = 'giropay',
}

/**
 * Schema for Type17Enum
 */
export const type17EnumSchema: Schema<Type17Enum> = stringEnum(Type17Enum);
