/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type26Enum
 */
export enum Type26Enum {
  Paywithgoogle = 'paywithgoogle',
}

/**
 * Schema for Type26Enum
 */
export const type26EnumSchema: Schema<Type26Enum> = stringEnum(Type26Enum);
