/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface UPICollect {
  /** The sequence number for the debit. For example, send **2** if this is the second debit for the subscription. The sequence number is included in the notification sent to the shopper. */
  billingSequenceNumber: string;
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** The `shopperNotificationReference` returned in the response when you requested to notify the shopper. Used for recurring payment only. */
  shopperNotificationReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  /** **upi_collect** */
  type: string;
  /** The virtual payment address for UPI. */
  virtualPaymentAddress?: string;
}

export const uPICollectSchema: Schema<UPICollect> = object({
  billingSequenceNumber: ['billingSequenceNumber', string()],
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  shopperNotificationReference: [
    'shopperNotificationReference',
    optional(string()),
  ],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  type: ['type', string()],
  virtualPaymentAddress: ['virtualPaymentAddress', optional(string())],
});
