/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type32Enum, type32EnumSchema } from './type32Enum';

export interface Vipps {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  telephoneNumber: string;
  /** **vipps** */
  type?: Type32Enum;
}

export const vippsSchema: Schema<Vipps> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  telephoneNumber: ['telephoneNumber', string()],
  type: ['type', optional(type32EnumSchema)],
});
