/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type15Enum, type15EnumSchema } from './type15Enum';

export interface Voucher {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** The shopper's first name. */
  firstName: string;
  /** The shopper's last name. */
  lastName: string;
  /** The shopper's email. */
  shopperEmail: string;
  /** The shopper's contact number. It must have an international number format, for example **+31 20 779 1846**. Formats like **+31 (0)20 779 1846** or **0031 20 779 1846** are not accepted. */
  telephoneNumber: string;
  /** **econtextvoucher** */
  type: Type15Enum;
}

export const voucherSchema: Schema<Voucher> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  firstName: ['firstName', string()],
  lastName: ['lastName', string()],
  shopperEmail: ['shopperEmail', string()],
  telephoneNumber: ['telephoneNumber', string()],
  type: ['type', type15EnumSchema],
});
