/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type35Enum, type35EnumSchema } from './type35Enum';

export interface WeChatPayMiniProgram {
  appId?: string;
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  openid?: string;
  /** **wechatpayMiniProgram** */
  type?: Type35Enum;
}

export const weChatPayMiniProgramSchema: Schema<WeChatPayMiniProgram> = object({
  appId: ['appId', optional(string())],
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  openid: ['openid', optional(string())],
  type: ['type', optional(type35EnumSchema)],
});
