/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type34Enum, type34EnumSchema } from './type34Enum';

export interface WeChatPay {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** **wechatpay** */
  type?: Type34Enum;
}

export const weChatPaySchema: Schema<WeChatPay> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  type: ['type', optional(type34EnumSchema)],
});
