/**
 * Adyen Checkout APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type36Enum, type36EnumSchema } from './type36Enum';

export interface Zip {
  /** The checkout attempt identifier. */
  checkoutAttemptId?: string;
  /** Set this to **true** if the shopper would like to pick up and collect their order, instead of having the goods delivered to them. */
  clickAndCollect?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  recurringDetailReference?: string;
  /** This is the `recurringDetailReference` returned in the response when you created the token. */
  storedPaymentMethodId?: string;
  /** **zip** */
  type?: Type36Enum;
}

export const zipSchema: Schema<Zip> = object({
  checkoutAttemptId: ['checkoutAttemptId', optional(string())],
  clickAndCollect: ['clickAndCollect', optional(string())],
  recurringDetailReference: ['recurringDetailReference', optional(string())],
  storedPaymentMethodId: ['storedPaymentMethodId', optional(string())],
  type: ['type', optional(type36EnumSchema)],
});
